### ISSUE TITLE
Removed tags still showing

### ISSUE THREAD

**Issue by FateXBlood** [hohMiyazawa/Automail#105]
Hello, 

I just found out that the stuff I had in my Notes section is still visible via the AutoMail script, which shouldn't be possible because I cleaned all of them long ago. Can you please tell me how to remove them? They're visible to everyone with the script and it looks super ugly.

Also, can you share how the tags are still there when I've removed them? Where are they stored?
![image](https://user-images.githubusercontent.com/30192697/137075324-5862a46b-0b9b-44c7-b1f1-74da551abca0.png)

**Comment by hohMiyazawa** [comment]
@FateXBlood I have seen no evidence that there were any tags from places that had been removed. Those two HxH entries were just examples, I found several others.

The script only ignores Mal-Sync tags were they are not relevant for what the script is showing. They are still there, and should not affect Mal-Sync users in any way.

Some way of clearing all notes is a feature I know several others are interested in, but I haven't got around implementing it yet.

**Comment by hohMiyazawa** [comment]
@FateXBlood Then something is hiding them for you.

1. Do the speech bubbles show up if you turn off Automail?
2. Do the speech bubbles show up in the other two list views?
3. Do the speech bubbles show up if you turn off your adblocker?
4. Those "2/12 [2]" things look non-default, and not part of Automail. Are you using some other scripts? Do the speech bubbles turn up if you turn those off?

**Comment by farahnur42** [comment]
Correction: MALSync *does* auto-hide the speech bubble but only when it only contains a MALSync tag, my initial test was incorrect. @hohMiyazawa
