### ISSUE TITLE
Don't show OP/ED when there are none

### ISSUE THREAD

**Issue by hohMiyazawa** [hohMiyazawa/Automail#106]
![oped](https://user-images.githubusercontent.com/58218853/137390215-cc2310e9-0a6b-45f4-9b40-d29580f2a05a.png)

This should probably not be shown.

@synthtech, you are more familiar with the code. Is this easy to get rid of?

**Comment by synthtech** [comment]
>Is this easy to get rid of?

It should be. I can probably push something soon.

I reported the issue with the api here: https://github.com/jikan-me/jikan/issues/366
