### ISSUE TITLE
Limited Functionality

### ISSUE THREAD

**Issue by An1meDweeb** [hohMiyazawa/Automail#112]
Hi, my script is broken. Here's the problems I found so far:

-Currently unable to see follower count, mutual followers, following/follower only, etc. 
- Unable to view custom CSS sitewide, unable to save CSS either
- Stat retrieval under "More Stats" does not work
- Review confidence scores don't appear

Issues came up overnight. Reset to default settings multiple times and updated Automail to the latest version multiple times, didn't work. Could you look into this? Thanks so much!

[jsonsettings_automail.txt](https://github.com/hohMiyazawa/Automail/files/7458425/jsonsettings_automail.txt)
![image](https://user-images.githubusercontent.com/93573118/139800171-66dba6a2-164b-4814-97c9-dd66503856b0.png)

**Comment by hohMiyazawa** [comment]
I notice your screenshot says "Donator", so you are presumably not using the stock Automail script.
Which modification are you using?

**Comment by An1meDweeb** [comment]
Oh I didn't modify the script, just removed the donator lines.

**Comment by hohMiyazawa** [comment]
Hm. The failures sound like API return failures. Anything of note printed to the console?

**Comment by An1meDweeb** [comment]
You've lost me there, I'm not too familiar with code heh
Is there anything you need me to check from my end?

**Comment by hohMiyazawa** [comment]
Inspect element > console

Sutff gets printed there if something's wrong. May help me get an idea of what's happening.

**Comment by richmond2010** [comment]
Nothing wrong with the script, it was a temporary API return failure. Another AL extension I was using was not working at the time too.

**Comment by An1meDweeb** [comment]
> Nothing wrong with the script, it was a temporary API return failure. Another AL extension I was using was not working at the time too.

Yup, everything's back to normal now. Checked with an AL user who lives in the same country as me, seems to have been a regional issue. Thanks!
