### ISSUE TITLE
Anime/manga-lists looking kind-of like a table(chart?) when vertical navbar is turned on

### ISSUE THREAD

**Issue by arrtemis** [hohMiyazawa/Automail#113]
I have noticed this issue while using the vertical navbar setting. When I turn it on, my lists start to have a white border line below each entry and start looking like a table; this specifically is a issue in Compact View of the list. I have included images bellow to better understand the issue

**when vertical navabar is off**
![image](https://i.imgur.com/Xc5Z289.png)
**when vertical navbar is on**
![eXEX65g](https://i.imgur.com/uz4HXYA.png)

As seen from the above images, this issue pops up only when turning on vertical navbar. So there's smth in the css(of vertical navbar) that's causing this and this should be separated from vertical navbar css since not everyone using the vertical navbar wants their lists to look like a microsoft word table.

But I wouldn't actually pin this down as a issue, because sometime ago @Koopzington mentioned this as being @hohMiyazawa's personal preference and that's totally understandable.

**Comment by arrtemis** [comment]
I have resolved this problem myself by commenting out

.medialist.table .row{
	border-bottom: solid;
	border-bottom-width: 1px;
	border-color: rgb(var(--color-text),0.5);
}
(line 4336-4340 in script)
with Tampermonkey's editor

anyone with this same issue can do the same by editing the script as I described above (but, be sure to keep a copy of the edited script as future updates yeet all edits lol)

**Comment by hohMiyazawa** [comment]
I'm still unsure what exactly should be done about this.

**Comment by arrtemis** [comment]
Sorry, I was not in the best of my moods when writing the body of this issue, so I think a rephrase is necessary here for this to make more sense imo.

**Comment by hohMiyazawa** [comment]
It would be too much having a separate module for all cosmetic changes, and in general, the vertical navbar module is the large pile of small changes that hoh prefers.

But I guess it looks nicer if they are less visible: https://github.com/hohMiyazawa/Automail/commit/297433e3cc75da90f6d9fc0b219de1c11cfe6606

**Comment by arrtemis** [comment]
yeah, that actually looks better than before.

**Comment by hohMiyazawa** [comment]
If that eases the issue, and since your workaround is documented here for those who absolutely don't like the table look, I think this is sufficiently dealt with for now.
