### ISSUE TITLE
Persistent green manga titles

### ISSUE THREAD

**Issue by arrtemis** [hohMiyazawa/Automail#114]
Even after I turn off the "Green titles for manga" the manga titles still appear in green color. 
![img](https://i.imgur.com/uPt62bW.png)
![img](https://i.imgur.com/oNlJgXs.png)

**Comment by hohMiyazawa** [comment]
https://github.com/hohMiyazawa/Automail/commit/e4a82cd4b7419031e0ff90d97b4cdf22bf577386
