### ISSUE TITLE
Colour code the right border of activities by media status not working

### ISSUE THREAD

**Issue by ViRo3** [hohMiyazawa/Automail#118]
Doesn’t work for attached configuration.
`{"socialTab":true,"socialTabFeed":true,"forumComments":true,"forumMedia":true,"staffPages":true,"tagDescriptions":true,"completedScore":true,"droppedScore":true,"studioFavouriteCount":true,"CSSfavs":true,"CSScompactBrowse":true,"CSSgreenManga":true,"CSSfollowCounter":true,"CSSprofileClutter":false,"CSSdecimalPoint":true,"CSSverticalNav":false,"CSSbannerShadow":false,"CSSdarkDropdown":true,"hideLikes":true,"dubMarker":false,"CSSsmileyScore":true,"feedCommentFilter":true,"feedCommentComments":0,"feedCommentLikes":0,"colourPicker":false,"colourSettings":[],"progressBar":true,"noRewatches":false,"hideCustomTags":false,"shortRomaji":false,"replaceNativeTags":true,"draw3x3":true,"newChapters":true,"limitProgress8":false,"limitProgress10":false,"tagIndex":true,"expandRight":false,"timeToCompleteColumn":false,"mangaGuess":true,"settingsTip":false,"MALscore":true,"MALserial":true,"MALrecs":true,"entryScore":true,"showRecVotes":true,"activityTimeline":true,"browseFilters":true,"embedHentai":true,"comparissionPage":true,"noImagePolyfill":true,"reviewConfidence":true,"blockWord":false,"showMarkdown":true,"myThreads":false,"dismissDot":false,"statusBorder":true,"moreImports":true,"plussMinus":true,"milestones":true,"allStudios":false,"CSSmobileExternalLinks":false,"termsFeedNoImages":true,"customCSS":true,"rightToLeft":false,"subTitleInfo":true,"customCSSValue":"","pinned":"","negativeCustomList":false,"globalCustomList":false,"betterListPreview":false,"homeScroll":true,"blockWordValue":"nsfw","hideGlobalFeed":false,"cleanSocial":false,"SFWmode":false,"hideAWC":false,"hideOtherThreads":true,"forumPreviewNumber":3,"profileBackground":true,"profileBackgroundValue":"inherit","viewAdvancedScores":true,"betterReviewRatings":true,"notificationColours":{"ACTIVITY_LIKE":{"colour":"rgb(250,122,122)","supress":false},"ACTIVITY_REPLY_LIKE":{"colour":"rgb(250,122,122)","supress":false},"THREAD_COMMENT_LIKE":{"colour":"rgb(250,122,122)","supress":false},"THREAD_LIKE":{"colour":"rgb(250,122,122)","supress":false},"THREAD_COMMENT_REPLY":{"colour":"rgb(61,180,242)","supress":false},"ACTIVITY_REPLY":{"colour":"rgb(61,180,242)","supress":false},"ACTIVITY_MESSAGE":{"colour":"rgb(123,213,85)","supress":false},"FOLLOWING":{"colour":"rgb(123,213,85)","supress":false},"ACTIVITY_MENTION":{"colour":"rgb(123,213,85)","supress":false},"THREAD_COMMENT_MENTION":{"colour":"rgb(123,213,85)","supress":false},"THREAD_SUBSCRIBED":{"colour":"rgb(247,191,99)","supress":false},"ACTIVITY_REPLY_SUBSCRIBED":{"colour":"rgb(247,191,99)","supress":false},"RELATED_MEDIA_ADDITION":{"colour":"rgb(247,191,99)","supress":false},"AIRING":{"colour":"rgb(247,191,99)","supress":false}},"staffRoleOrder":"alphabetical","titleLanguage":"ROMAJI","dubMarkerLanguage":"English","accessToken":"[REDACTED]","automailAPI":false,"comparisionColourFilter":true,"comparisionSystemFilter":false,"annoyingAnimations":true,"navbarDroptext":true,"browseSubmenu":false,"reinaDarkEnable":false,"customDefaultListOrder":"","softBlock":[],"partialLocalisationLanguage":"English","dblclickZoom":true,"addForumMedia":true,"additionalTranslation":false,"moreStats":true,"ALbuttonReload":true,"anisongs":true,"autoLogin":true,"clickableActivityHistory":true,"directListAccess":true,"characterFavouriteCount":true,"notifications":true,"enumerateSubmissionStaff":true,"expandDescriptions":true,"expandedListNotes":true,"CSSexpandFeedFilters":true,"extraDefaultSorts":true,"extraFavs":true,"feedListLikes":true,"filterStaffTabs":true,"forumLikes":true,"forumRecent":true,"forumVisualLikes":true,"hollowHearts":true,"imageFreeEditor":true,"infoTable":false,"interestingRecs":true,"keepAlive":true,"mangaBrowse":false,"markdownHelp":false,"mobileFriendly":true,"CSSmobileTags":true,"noAutoplay":false,"nonJapaneseVoiceDefaults":true,"nonJumpScroll":true,"noScrollPosts":true,"CSSoldDarkTheme":false,"randomButtons":true,"rangeSetter":true,"reinaDark":true,"relations":true,"replaceStaffRoles":false,"rightSideNavbar":false,"settingsPage":true,"singleActivityReplyLikes":true,"slimNav":false,"termsFeed":true,"tweets":true,"twoColumnFeed":false,"unicodifier":true,"videoMimeTypeFixer":false,"webmResize":false,"yearStepper":true,"youtubeFullscreen":true,"howto":false,"loginAttempted":true} `

**Comment by hohMiyazawa** [comment]
Screenshot of what the home feed looks like?
Anything special printed to the terminal?

**Comment by ViRo3** [comment]
![E3EC5F90-9CF5-406D-B663-FFA8820E1FA1](https://user-images.githubusercontent.com/87166847/144153947-a9def191-0f3a-4cbd-9a41-6dcacf5df5bf.png)

console : 
BroadcastChannel not available. Automail will not be able to share cached data between tabs

**Comment by hohMiyazawa** [comment]
Ah, it's the mobile view.

Looking at the code, the status borders are among the modules that get disabled there, since they don't work well with the layout.

It can probably be made to work okay on mobile, but that's a TODO.
