### ISSUE TITLE
Update broke Automail on Macaque (iOS/iPadOS)

### ISSUE THREAD

**Issue by ViRo3** [hohMiyazawa/Automail#122]
[Changes](https://greasyfork.org/en/scripts/370473-automail/diff?v1=994390&v2=993860) between .72 and .71 broke Automail on [Macaque](https://apps.apple.com/in/app/macaque/id1595306197) user-script manager.

**Comment by evanreichard** [comment]
This is the diff that fixes it for me: https://gist.github.com/evanreichard/7e73b65bb7ffbc3ab9bf915324b93ee4/revisions

It doesn't crash on other browsers because they don't hit that logic block (Safari doesn't have `window.BroadcastChannel`)

**Comment by hohMiyazawa** [comment]
https://github.com/hohMiyazawa/Automail/commit/51c861e0c1153e42a1324991ffe6a01d876045f4
