### ISSUE TITLE
[Suggestion] BBCode to Anilist Markdown Conversion

### ISSUE THREAD

**Issue by grravity** [hohMiyazawa/Automail#13]
Suggesting the ability to type out in traditional BBCode (Ex. `[b]bold[/b]` instead of anilist's `_bold_`) for people who enjoy/prefer/are used to typing in BBCode. And as your typing it changes it to anilist's flavor in the preview and the submission. Obviously it'd only support what Anilist has avaliable for comparable options. But if someone wants to use `[b]bold[/b]` instead of `_bold_` they can.

Maybe alongside this, an option to hide Anilist's "easy formatting" options (the buttons you can click while typing, such as B for bold, i for italics, the Youtube icon for youtube, etc.

**Comment by hohMiyazawa** [comment]
This would likely involve replacing all input widgets, to stay consistent.
I'm not familiar enough with BBCode to write this.

Pull requests welcome.

**Comment by hohMiyazawa** [comment]
After considering the problems this could lead to, I have decided that this is not worth it.
Use an external tool to convert you BBCode to markdown.
