### ISSUE TITLE
Target a specific ECMAScript standard?

### ISSUE THREAD

**Issue by hohMiyazawa** [hohMiyazawa/Automail#135]
Using newer features, particularly syntax, comes at the risk of less compatibility with various browsers found in the wild.
Particularly, some ES11 features aren't all that common yet.

The only ES10 features used now seems to be ``Array.prototype.flat()``, which can be polyfilled.

I propose targeting ES9.

**Comment by hohMiyazawa** [comment]
Major problems with supporting ES8 is the spread operator ``...`` and rest parameters in ES9 though it should be noted popular browsers supported these a long time in advance.

**Comment by hohMiyazawa** [comment]
``await``, ``async`` from ES7 are probably essential, though ``Array.prototype.includes`` is polyfilled, and ``**`` is avoided through using ``Math.pow`` instead.

**Comment by synthtech** [comment]
>I propose targeting ES9.

I suppose that's fine.

I feel like this will eventually be hard to maintain without better tooling to transpile down to the targeted version.

**Comment by hohMiyazawa** [comment]
I feel that when the compatibility target get too ancient and unpleasant to maintain, we just increment it, since browsers have probably caught up by then.

**Comment by hohMiyazawa** [comment]
@synthtech Is there some non-intrusive tooling that would allow transpiling individual modules?
Then using newer features would be fine.

**Comment by hohMiyazawa** [comment]
Ideally, it would not be something that's needed to make a working build. That is:
- Without tool: build will only work in newer browsers
- With tool: build will optionally work in older browsers

**Comment by synthtech** [comment]
>Is there some non-intrusive tooling that would allow transpiling individual modules?

Aha, good question, honestly all the tools I've seen before depend on the Node.js ecosystem. (also I think most tools expect modules to be ESM modules which is another difficulty)

>Ideally, it would not be something that's needed to make a working build.

I mean, I need Linux installed just to build the project currently. Anyways, from what I remember you could have the individual files use whatever language features are available (es10+) and then the build would always be whatever version you configured (es9).

---

I know I mentioned transpiling earlier as it's the first thing that came to mind, but it could be less complicated to instead "correct" the code with a linter using something like this:
https://github.com/amilajack/eslint-plugin-compat

This way code before and after building can remain es9 and you can receive a warning if using features beyond the target version.

Quote from the above link kinda sums up what I want lol:
>to save web developers from having to memorize the browser compatibility of WebAPIs.

**Comment by hohMiyazawa** [comment]
> I mean, I need Linux installed just to build the project currently.

Which is not good from a point of making it easy to tinker. Do you have some build system ideas? https://github.com/hohMiyazawa/Automail/issues/136

There's also [this](https://github.com/hohMiyazawa/Automail/issues/5), but I'm not sure how it all ties together.

**Comment by hohMiyazawa** [comment]
> I know I mentioned transpiling earlier as it's the first thing that came to mind, but it could be less complicated to instead "correct" the code with a linter using something like this:
https://github.com/amilajack/eslint-plugin-compat

Do you have experience setting this up? If it's something that can *optionally* be run, to check that we're still compatible, that sounds great.

**Comment by synthtech** [comment]
>There's also #5, but I'm not sure how it all ties together.

For my current setup, I've opted to use Ubuntu via [WSL2](https://docs.microsoft.com/en-us/windows/wsl/install) just for the build step.

>Do you have experience setting this up?

For this plugin, no. For the eslint linter, yes. I think it would be easy to setup.

>If it's something that can optionally be run, to check that we're still compatible, that sounds great.

For the linter, yea it can be completely optional that doesn't require any changes to the current build system.
