### ISSUE TITLE
Slim down build dependencies

### ISSUE THREAD

**Issue by hohMiyazawa** [hohMiyazawa/Automail#136]
As is well known, the more tools needed to build a project, the harder it is to get into.

Is there any tool in the current build process that could be dropped?
Currently, a makefile is used, with m4 as the build system
Executables: ``sed rm mkdir date zip m4 cp cat``
Could this be simplified?
Could alternative workflows be made, which has wider support?

**Comment by synthtech** [comment]
>Could this be simplified?

While I've never really looked closely at the build scripts before, it seems to work well currently. I only recall having to install `m4` and `make` as they weren't there by default.

>Could alternative workflows be made, which has wider support?

I see bundlers being used a lot such as:
[swc](https://swc.rs/), [rollup](https://rollupjs.org/guide/en/), [esbuild](https://esbuild.github.io/) + hundreds more
These tools seem to be designed to "bundle" together ES modules amongst other features. They can potentially be configured to act as an alternative build system. I've never used them before though, so I have no idea how difficult it is.
- Upside: Cross-platform
- Downside: More bloat (probably)

If the addon is still supported, Mozilla provides a CLI tool for packaging webextensions:
https://github.com/mozilla/web-ext
