### ISSUE TITLE
Set up linting tool

### ISSUE THREAD

**Issue by hohMiyazawa** [hohMiyazawa/Automail#137]
It would be convenient to have a linting tool, as mentioned in https://github.com/hohMiyazawa/Automail/issues/135, to make sure we don't loose compatibility with any major platform.

**Comment by synthtech** [comment]
I recently setup [eslint](https://eslint.org/) on my own branches as I'm rewriting stuff. So, I could probably make a PR soon with the previously mentioned plugin unless a different linter is preferred.

**Comment by hohMiyazawa** [comment]
I have no reason to prefer a different linter.

**Comment by hohMiyazawa** [comment]
@synthtech Looking into it, isn't the minimal linter setup just to have a ``.eslintrc.json`` file, and that's it? People can install and run eslint if they want. But the plugin idea sounds interesting, so go ahead.

**Comment by synthtech** [comment]
Yea, though it requires installing the tool globally which is generally not recommended.

**Comment by hohMiyazawa** [comment]
How is that different from any other executable?

**Comment by synthtech** [comment]
iirc global packages are just a wrapper around a command like `node .../eslint.js` or something, so there is no actual binary file.

Having the package be self-contained prevents issues where different projects expect different versions of the same package.

![](https://share.wildbook.me/Ad8qVyDnaHaN93dM.png)

e.g. if my other project was previously configured with v7.x of eslint globally and v8.x was installed instead, it could run into unexpected issues

I think it would still be fine to install globally if Automail is the only project a user is using the tools with, so I could add alternative instructions for that.
