### ISSUE TITLE
CSS profile 

### ISSUE THREAD

**Issue by itsuki1simp** [hohMiyazawa/Automail#139]
Did i miss something? "Enable custom profile CSS and pinned activities" appears grayed out and i can't find the box where I should put the css script

**Comment by hohMiyazawa** [comment]
Those require extra privileges, as do all the modules greyed out and in the login tab.

Click the "Sign in with the script" link on the bottom of the settings page to activate them.

**Comment by itsuki1simp** [comment]
Thank you so much!
