### ISSUE TITLE
Unable to open profile with the script enabled

### ISSUE THREAD

**Issue by FateXBlood** [hohMiyazawa/Automail#153]
Hello, this problem arose a few hours ago from me writing this post. 

I have been unable to access my profile with the script enabled. Everything else works totally fine: Home, AnimeList, MangaList, Notifications. I can access my profile via incognito mode. 

I'm on Chrome's latest version and have no CSS in my profile. Someone else is also facing this issue so I know I'm not alone in this.

**Comment by hohMiyazawa** [comment]
What exactly does "unable to access my profile" mean?

Can I get a screenshot of what's wrong? Example URLs?

**Comment by FateXBlood** [comment]
![image](https://user-images.githubusercontent.com/30192697/152850384-926bfc14-8eb4-4e05-b9c5-1de784d2fdd1.png)
This is pretty much what happens when I go to my profile or anyone else's. After a few seconds, Chrome sends a message that the page has become unresponsive.
![image](https://user-images.githubusercontent.com/30192697/152850563-f7039684-dddf-49c5-bbb2-fca39681faa6.png)

**Comment by S-NicoX** [comment]
Same, I can't open neither my profile nor other profiles with script enabled. It just freezes chrome.

**Comment by hohMiyazawa** [comment]
I think I must have made a horrible mistake...

**Comment by hohMiyazawa** [comment]
Cause likely found

https://github.com/hohMiyazawa/Automail/commit/38070e829e1852da612b2591abbc463d0c9e8f90

**Comment by hohMiyazawa** [comment]
v10.0.8 is live, should fix the issue

**Comment by FateXBlood** [comment]
Yep, everything is fixed now. Thanks. 
By the way, any way to fix this All, Status, etc to be like how it was before, in drop-down menu? @hohMiyazawa 
![image](https://user-images.githubusercontent.com/30192697/152852479-f1fd3a25-7277-472b-b075-f08d5a30cabf.png)

**Comment by hohMiyazawa** [comment]
@FateXBlood Should be a setting called "Expand the feed filters".
