### ISSUE TITLE
Check compatibility with all following (slow)

### ISSUE THREAD

**Issue by FlammFR** [hohMiyazawa/Automail#159]
Idk if it's just me but when i run this command in More Stats for example List Type: Anime, i can't do it for manga without opening a new tab, and vice versa

**Comment by FlammFR** [comment]
> You mean, first running it for anime, and then when running it again changed to manga, it doesn't work?
 
Yes. In fact, the command is started but no result is displayed

**Comment by FlammFR** [comment]
> Alternatively, it may be the manga version that's broken.

I have the same problem when I start with the manga version then try the anime version

**Comment by hohMiyazawa** [comment]
Solved. Automail was using the wrong cached list, causing switching between the queries to not work.
