### ISSUE TITLE
Related anime/manga not on list

### ISSUE THREAD

**Issue by FlammFR** [hohMiyazawa/Automail#160]
"Found _ anime" is always incorrect, even including media related to dropped anime, same for manga

**Comment by hohMiyazawa** [comment]
Okay that clearly wrong. Will look into what happens with the filtering there.

**Comment by hohMiyazawa** [comment]
Solved. Automail was using the wrong list cache, causing switching between queries to not work properly.

**Comment by hohMiyazawa** [comment]
Solved.

Thank you for the bug reports. A new version will be online soon.
