### ISSUE TITLE
Unable to import custom css with github

### ISSUE THREAD

**Issue by Yashirow** [hohMiyazawa/Automail#162]
First of all I've already read this [issue](https://github.com/hohMiyazawa/Automail/issues/27) but I can't import my css or someone else's with Github (raw.githubusercontent ...).
It works if I copy and past the same code tho.
I just need to past the url, right ? Or am I doing something wrong ?

**Comment by hohMiyazawa** [comment]
Same as in that thread, github sends some HTTP headers that tells browsers to not use the linked file as a stylesheet.
Host it somewhere else, or just pase the entire thing like you do.

**Comment by Yashirow** [comment]
Thank you for clarifying, I thought it was fixed ; the last message of the issue confused me.
