### ISSUE TITLE
"Time Watched" stat doesn't show if you don't rate

### ISSUE THREAD

**Issue by samsamsamurai** [hohMiyazawa/Automail#163]
It seems like the "Time Watched" stat in the "More Stats" section is lumped together with the rating related stats, so it won't show if you don't rate

**Comment by hohMiyazawa** [comment]
This should probably be enough?:

https://github.com/hohMiyazawa/Automail/commit/846e0df8d9e56dfba4e2a4f39f21dca92ce620e5

**Comment by samsamsamurai** [comment]
I don't think this fixed it, in fact it now only shows the "Anime on list" and "Anime rated" stats. I believe the issue is related to singleText being only defined inside the if-statement which begins on line 954

**Comment by hohMiyazawa** [comment]
Yep, I'm an idiot
