### ISSUE TITLE
[Suggestion] Sync From AniDB | Hentai Icon on Lists

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [hohMiyazawa/Automail#17]
_First I want to start by bumping my old request for a hentai icon on lists. Just a tiny small icon to quickly identify hentai. (Something like a small icon of pink lips or something)._

And my **main suggestion being implementation of being able to grab user list updates from Anidb.**
I would _assume_ this can even be done without needing a sign in to Anidb. Just type the username you want to monitor on anidb, then when they update their list on anidb, it updates your anilist list. Or just sign in to Anidb. But I think the monitoring is better (if possible) for the sole reason of not needing to sign in just to limit security risks.

**So as an example:**

AniDB `User`: `SSSS-Gridman, Watched Episodes 1 to 3.`
Updates your list on Anilist to show you watched episodes 1 to 3 of SSSS-Gridman.

This would obviously apply to ratings and whatever else it can grab from AniDB.

The benefit of this would be allowing users to use AniDB for their main database tracking. Using AniDB as a backup/secondary. Also keeping connections on Anilist, allowing users on Anilist to stay up to date with what you're watching, not having to manually update both lists. AniDB quite honestly offers way more in options of tracking (Whether you have a series saved on your hdd, remote storage, etc.) just as an example.

**Comment by hohMiyazawa** [comment]
*The hentai icon thing may happen*

But syncing with AniDB is currently way out of scope for what Automail does. Importing lists may be possible, but I can's see any reasonable way to sync activities through the script.
