### ISSUE TITLE
Prority for lists 

### ISSUE THREAD

**Issue by Cikapkamuy** [hohMiyazawa/Automail#170]
A way for users to have a custom order for their lists.

**Comment by hohMiyazawa** [comment]
Only for custom lists, or for the native lists (completed, watching, etc.), too?

**Comment by Razi1660** [comment]
For custom lists I suppose.

**Comment by hohMiyazawa** [comment]
I don't know how to implement this.

**Comment by nategasm** [comment]
I think this could be done but it would probably be a fair amount of work.

On the AM settings page, query/display a list of the user's lists and let the user reorder it.
On the user list page, read the user's configured list order and re-arrange them on the page with something like insertBefore(),

Of course there's also many variables and scenarios to consider.

**Comment by Yakaita** [comment]
Am I the only one who doesn't understand the request? You can already order your lists how you want on Anilist vanilla or is this different?

**Comment by nategasm** [comment]
> Am I the only one who doesn't understand the request? You can already order your lists how you want on Anilist vanilla or is this different?

Yeh you're right, ignore my post
