### ISSUE TITLE
Activity history missing on some manga

### ISSUE THREAD

**Issue by arrtemis** [hohMiyazawa/Automail#171]
i have been noticing this issue for a while, but i thought it's cuz i was on an outdated version. but even after update, the issue is still there. Some manga have the activity history section just fine.
![](https://files.catbox.moe/znbvu7.png)

But on a few manga it's completely missing, note that these are manga i am sure I have a lot of activity for
![](https://files.catbox.moe/ziz2de.png)

**Comment by arrtemis** [comment]
i was using Japanese titles and my guess is automail was probably unable to match activity with respective entry cuz of title difference (since i was using Romaji before)

so, the activity timeline works fine again by switching back to romaji title

**Comment by hohMiyazawa** [comment]
Should be working for japanese too.

I will investigage

**Comment by hohMiyazawa** [comment]
Was a regex issue. Fixed.

https://github.com/hohMiyazawa/Automail/commit/cc733b53c7fa0ffb7b73b0205ac5d95fe682ded3
