### ISSUE TITLE
How does the 3x3 maker work?

### ISSUE THREAD

**Issue by TheInternetUser0** [hohMiyazawa/Automail#178]
I could not find a clear instruction.

**Comment by TheInternetUser0** [comment]
Never mind. I was able to figure it out. Works nicely thanks. But still, an instruction would be nice.

**Comment by hohMiyazawa** [comment]
Yeah, it's one of the things that were coded up in 5mins when needing a 3x3, and never updated since.

**Comment by hohMiyazawa** [comment]
Replaced with a new and better one.
