### ISSUE TITLE
Broken Activity feed formatting with restricted messaging

### ISSUE THREAD

**Issue by nategasm** [hohMiyazawa/Automail#180]
It seems when you view a user that has restricted messaging turned on, it breaks their activity feed. (Both 1 and 2 columns)
Example user: https://anilist.co/user/mebiusash
![ActivityFeedBug](https://user-images.githubusercontent.com/28376248/178137500-33f25e79-6e95-413a-978b-8c2f16aa8ff2.JPG)

**Comment by hohMiyazawa** [comment]
Can't reproduce. Settings file?

**Comment by nategasm** [comment]
[Automail_settings.zip](https://github.com/hohMiyazawa/Automail/files/9078835/Automail_settings.zip)
Attached but also does it with default settings. Happens in both FF and Edge (Tampermonkey with other extensions/scripts disabled)

**Comment by hohMiyazawa** [comment]
Likely fixed v10.3.2

https://github.com/hohMiyazawa/Automail/commit/5f391c50a453e83d4f2aa5e8f6fad5aa008d7010
