### ISSUE TITLE
hoh's version of staff pages doesn't respect AniList's Title & Name Language options

### ISSUE THREAD

**Issue by blueYOSHI9000** [hohMiyazawa/Automail#185]
When enabling "Hoh's version of sortable staff pages" it no longer respects the "Title Language" and "Staff & Character Name Language" options from AniList itself. Titles will always be displayed in "Romaji" and names are always in "Romaji, Western Order".
Both options are found under "Anime & Manga" in AniList's settings.

**Comment by hohMiyazawa** [comment]
Thanks, looks like the titlePicker isn't doing what it should here. Title language is usually handled correctly in the script.

The staff & character setting is newer thant the script module in question, so support was never implemented. Will look at both.

**Comment by hohMiyazawa** [comment]
Title language should be fixed now
