### ISSUE TITLE
Can't access automail settings in turkish language

### ISSUE THREAD

**Issue by kyoyacchi** [hohMiyazawa/Automail#186]
Hi. I can not access settings of Automail in Anilist.
I check in devtools, it says these
![Screenshot_20221010-153136](https://user-images.githubusercontent.com/63583961/194866993-d533ece2-e83d-49db-9f5e-234b00b1baa7.jpg)
![Screenshot_20221010-153138](https://user-images.githubusercontent.com/63583961/194867060-273d263e-e2f4-4411-b1d8-e4abaf2aa813.jpg)

I uninstalled and re-installed script but didn't work. 
I am using Violentmonkey in kiwi browser.

**Comment by kyoyacchi** [comment]
I manage to access with clearing cache of AniList. Sorry.

**Comment by kyoyacchi** [comment]
I noticed that i can't access to automail settings by setting language to Türkçe(Turkish), no problem for English (didn't try other langs)

**Comment by hohMiyazawa** [comment]
Those errors come from the the translation framework, not sure wha the root cause is.
But I could probably make the script just skip whatever translation it is attempting then, and not crash.

**Comment by hohMiyazawa** [comment]
v10.3.9 Should make this kind of key failures not take the whole settings page down
https://github.com/hohMiyazawa/Automail/commit/4524c9d037df0f096fa85a2f0cb7b114fe9bd895
