### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by StilesClover** [hohMiyazawa/Automail#19]
Hey :) i just found out today about this script and i really like it but there is one thing i really want and the others i don't know if its possible ^^

1. I really like the vertical navbar but i don't like that its on the left side :/ it would be great if we get an option to put it on the right side. I could activate the right to left flow option but that changes everything so its not what i want :/ 

2. If its possible it would be nice if we can set the default list order to completed or started date. 

3. I don't know how hard this would be to make but it would be awesome if there would be an stats option that shows you how many episodes you watched in a year. Anilist only shows how many episodes you watched in the year where you started this title so this is not really good. The only way this can work if the script is looking though your whole activity and detects every title and the highest episode count. 

4. An on/off option for the browse/list where the script combines every title in an "folder" based on the anime series. And if you click on on of these "folders" you get a little dropdown menu where every title (Sequel, OVAs, Specials etc.) is in one place.

**Comment by StilesClover** [comment]
5. It would be awesome if the position of the "Custom Lists" in the list editor could be placed on the top (over the picture and the save button and it should be from left to right). 

Well on the picture the editor is a bit bugged but i have so many custom list (and i bet i'm not alone with this ^^) so this would make it so much easier to use.

[Picture](https://ibb.co/XxhJJSM)

**Comment by hohMiyazawa** [comment]
1. This is possible to implement, although it may take some work before it's entirely stable. Not a priority.

**Comment by hohMiyazawa** [comment]
2. Not possible without completely replacing the native lists. Send a feature request to Anilist instead.

**Comment by hohMiyazawa** [comment]
3. I have considered various versions of this before, but haven't found it worthwhile.

**Comment by hohMiyazawa** [comment]
4. Needs more details. Difficulty of implementation varies a lot by what you actually want this one to do.

**Comment by hohMiyazawa** [comment]
5. Not sure if they would fit. The solution Automail provides to too many custom lists is custom tags. Need more details.

**Comment by hohMiyazawa** [comment]
Right side navbar coming in 9.14, testing it now.

As none of the others are possible or clear enough at the moment, I'm closing this.
