### ISSUE TITLE
Failed to save custom CSS

### ISSUE THREAD

**Issue by Celarye** [hohMiyazawa/Automail#190]
Recently custom CSS won't show up for me anymore. My CSS file is fine.

This is the pop-up I get when i try to load the CSS in the automail settings.
![image](https://user-images.githubusercontent.com/96624179/201444943-948e4f95-3077-43b4-8883-0501a89109c9.png)

**Comment by hohMiyazawa** [comment]
Can you post the CSS here?

**Comment by Celarye** [comment]
Just opened AniList and it seems to be working again by itself. Sorry for the inconvenience.

**Comment by Celarye** [comment]
Well now it's happening again... Maybe it has something to do with [this](https://twitter.com/AniListco/status/1591127717130686464)?
Anyways, here is my css file: [Anilist.zip](https://github.com/hohMiyazawa/Automail/files/9998082/Anilist.zip)

**Comment by hohMiyazawa** [comment]
Could be, the API is the first thing that gets shut down.

Not seeing anything unusual in that CSS, works for me.

Not sure if it's possible to give more feedback than that *something* failed.
