### ISSUE TITLE
[Feature Request] Download user's banner

### ISSUE THREAD

**Issue by kyoyacchi** [hohMiyazawa/Automail#191]
Hi. 
I'd like to download the user banner via Automail, somehow.

For example, i think it'd be good to have a button or something like that at right top corner in any user's profile. I couldn't think better, i know.

There is a script that lets me download any user's banner but it opens banner in new tab every time when i visit any user's profile.

I tried to write it by myself, but it felt hard than it looks.

**Comment by hohMiyazawa** [comment]
This is already a thing, there's a little ``⭳`` button on the top right corner of profiles.

**Comment by kyoyacchi** [comment]
> This is already a thing, there's a little `⭳` button on the top right corner of profiles.

No, it's absent. I can't see it. Is it a emoji?
![Screenshot_20221203-221900](https://user-images.githubusercontent.com/63583961/205458098-0528342d-f3d6-4272-aff5-2152bc1b7699.jpg)
I only see this.

**Comment by kyoyacchi** [comment]
![Screenshot_20221203-222712](https://user-images.githubusercontent.com/63583961/205458403-2800745a-0dfb-4960-a17b-4e0e7e022410.jpg)

**Comment by hohMiyazawa** [comment]
Looks like a font problem.
Luckily, I have a way of checking if glyphs render or not, so I can add a fallback. Does ``↓`` work for you?

**Comment by kyoyacchi** [comment]
> Looks like a font problem. Luckily, I have a way of checking if glyphs render or not, so I can add a fallback. Does `↓` work for you?

Yes it does

**Comment by hohMiyazawa** [comment]
https://github.com/hohMiyazawa/Automail/commit/e348d1df09492d31e2974067ac665210b60bcbbe

**Comment by kyoyacchi** [comment]
> [e348d1d](https://github.com/hohMiyazawa/Automail/commit/e348d1df09492d31e2974067ac665210b60bcbbe)

Uh...
![Screenshot_20221203-223629](https://user-images.githubusercontent.com/63583961/205458699-f1671144-d2a8-4dbd-aa2f-901a63517c32.jpg)

![Screenshot_20221203-223652](https://user-images.githubusercontent.com/63583961/205458737-cb73b33a-f8b6-4b1c-b906-33e7c74b81df.jpg)

Is this normal?
