### ISSUE TITLE
Tags of own profile don't show up when logged in

### ISSUE THREAD

**Issue by 466gaming** [hohMiyazawa/Automail#20]
So this problem seems to have started a few days ago.

I can view other users' tags on their profiles;
![image](https://user-images.githubusercontent.com/17676761/75587258-febdad00-5a6d-11ea-8f6c-09ea89afa4eb.png)
but my tags don't show up on my own profile;
![image](https://user-images.githubusercontent.com/17676761/75587301-12691380-5a6e-11ea-8a90-04e5106d0795.png)

Just to make sure it wasn't an issue with my profile in particular or an issue with cookies or cache, I looked at my profile in incognito mode, and sure enough, my tags show up;
![image](https://user-images.githubusercontent.com/17676761/75587393-45130c00-5a6e-11ea-95b9-917f3369271d.png)
so I made a temporary test account in incognito too, added a series to my list, and added a tag;
![image](https://user-images.githubusercontent.com/17676761/75587429-5cea9000-5a6e-11ea-9c28-84fa477bad4a.png)
it doesn't show up while I'm logged into the account;
![image](https://user-images.githubusercontent.com/17676761/75587442-65db6180-5a6e-11ea-98e5-533497f13378.png)
but it *does* show up if I view the account from a normal window (or if I log out of the account, presumably);
![image](https://user-images.githubusercontent.com/17676761/75587517-8a373e00-5a6e-11ea-8f8d-4dd81e786e36.png)

**Comment by hohMiyazawa** [comment]
Can't reproduce, but I'm pretty sure where this issue comes from.

Due to your list data being available to the script while logged in, Automail "cheats", and fetches the data from your cache instead of requesting it from Anilist (it's faster).

However, there may be something about your storage permissions for the cache. Can you do the following?:

1. Open the dev tools. (while on Anilist
2. Go to the "storage" tab
3. Select "indexedDB".
4- Under the anilist domain, is "automail" listed?

Also of interest, can you do right click > site info > permissions, what does it say about storage?

Will try to make a fallback solution.

**Comment by hohMiyazawa** [comment]
Relevant part of the code: from "drawListStuff.js" (needs a better name....)

```javascript
if(variables.name === whoAmI){
	cache.getList(variables.listType,function(data){
		collectNotes({
			data: {
				MediaListCollection: data
			}
		})
	})
}
else{
	generalAPIcall(
		queryMediaListNotes,
		variables,
		collectNotes,
		"hohCustomTagIndex" + variables.listType + variables.name,60*1000);
}
```

**Comment by hohMiyazawa** [comment]
Relevant code from cache.getList in "cache.js"

```javascript
getList: function(type,callback){
	if(!cache.list[type]){
		cache.lockedCallbacks[type].push({callback: callback,type: type})
		if(!cache.lock[type]){
			localforage.getItem("automailListCache" + type,function(err,value){
				if(err){
					console.log(err);
					return
				}
				if(value){
					if(NOW() - value.time > value.duration){
						cache.forceUpdate()
					}
					else{
						cache.list[type] = value;
						cache.lockedCallbacks[type].forEach(a => a.callback(cache.list[a.type].data));
						cache.lockedCallbacks[type] = [];
					}
				}
				else{
					if(cache.lock.ANIME !== cache.lock.MANGA){
						cache.forceUpdate()
					}
				}
				cache.lock[type] = true;
			})
		}
	}
	else{
		callback(cache.list[type].data)
	}
}
```

**Comment by hohMiyazawa** [comment]
Seeing that possible console.log(err) logging, is anything printed to your console when viewing your list while logged in?

**Comment by hohMiyazawa** [comment]
Reproduced after blocking data storage for Anilist in Firefox.

I'm writing some code to check if data storage has been blocked, and if that's the case, use the regular way of loading the tag index.

**Comment by hohMiyazawa** [comment]
Patched in v9.13
Users who disable persistent storage will now still get the tag index on their own page.

**Comment by nukirisame** [comment]
I'm having a similar issue, except with the full list of tags on the stats page stuck endlessly loading. I can view other accounts' extra stats just fine, and also my own while in incognito.

![image](https://user-images.githubusercontent.com/68613178/91923187-a63ec500-ecc7-11ea-9620-e44d8377c48a.png)

I'm using Chrome, but I just tried it on Firefox (with persistent storage turned on) and it's still stuck loading. Any ideas?

**Comment by nukirisame** [comment]
On top of the denied persistent storage message, I'm getting the error "POST https://graphql.anilist.co/ 404" which I'm guessing has to do with the url changing to https://anilist.co/graphiql

**Comment by hohMiyazawa** [comment]
@nukirisame These two things can't be possible at the same time: "with persistent storage turned on" and "the denied persistent storage message". Can you clarify whether you are actually allowing the script to keep list data at hand or not?
https://anilist.co/graphiql is just an IDE, the API is still at https://graphql.anilist.co/ (or so the documentation says).

**Comment by nukirisame** [comment]
That was with Chrome where persistent storage isn't an option. On Firefox the denied persistent storage message is gone, but the "POSThttps://graphql.anilist.co/" is still there.

**Comment by hohMiyazawa** [comment]
Then I'm afraid I can't think of anything I can do, unless you can provide steps for how to reproduce this problem.
