### ISSUE TITLE
Offer a setting to change default options for rating comparisons

### ISSUE THREAD

**Issue by 466gaming** [hohMiyazawa/Automail#21]
It'd be nice if there was a setting to set these options for rating comparisons by default:
![image](https://user-images.githubusercontent.com/17676761/75630870-2df72a00-5be6-11ea-957c-5ab0dc972a8b.png)
since I find myself setting the options to the ones above every time I view score comparisons.

**Comment by hohMiyazawa** [comment]
Not sure about making it an option, but it could default to what you last used, like the sorting options on staff pages.

**Comment by hohMiyazawa** [comment]
Implemented that way. "Colour entire cell" is also turned on by default.

https://github.com/hohMiyazawa/Automail/commit/755f1fdbeedaa8426c1c91da2bebd1cf8f474a5c
