### ISSUE TITLE
Translator mode

### ISSUE THREAD

**Issue by alsoGAMER** [hohMiyazawa/Automail#211]
Considering that most of the time, translators (like me) have no idea about the context of a string, it would be great if a Translator mode would be added to be toggled on by us.

That mode should basically consist in the addon/script using the raw key names from the english localization file, instead of the value of the keys themselves.
Example: 
![image](https://user-images.githubusercontent.com/35269770/212164474-03acc056-fe56-4002-bdde-c5937481650e.png)

**Comment by hohMiyazawa** [comment]
Good idea.

**Comment by hohMiyazawa** [comment]
Implemented this by making a language called ``$raw_keys [(translator mode)]``

https://github.com/hohMiyazawa/Automail/commit/2c447008b9029dc2b76d282923a6456144a0cffa

**Comment by hohMiyazawa** [comment]
And it's online

**Comment by alsoGAMER** [comment]
That was quick, thank you!
