### ISSUE TITLE
Making time stamps visible

### ISSUE THREAD

**Issue by Damselflies** [hohMiyazawa/Automail#213]
So this is a question/feature request (depending on if it exist or not)
To give some context, I’m currently without a computer and only have my ipad/android phone, using automail on the ipad.
There are some features of anilist that require you to hover over something, which is simply impossible on any touch device. I would like to know the exact date of a forum post I made and well, I would like to know it more specific than; 2 years ago.
So if there anyway to get the time stamp visible you normally have to hover over the text for ? If not it might be a good addition to add, which you can turn on in settings you dont have to hover over anything to get the additional information. 

Thanks

**Comment by hohMiyazawa** [comment]
I can try, though I don't have a touch device to make tests on.

(question: how does one install the script on an ipad?)

**Comment by Damselflies** [comment]
Im glad u asked lmao, first had to download Stay - Userscript Extension , then enable it for safari, then download the script from Greasyfork. It took a bit of research to find how I could do it but glad I found a way. It doesn’t work 100%/takes some time with moments, but Im satisfied enough to be able to use it.

I personally don’t really know a lot about coding so can’t really help on that part. But I think the easiest way might be to just put the information you get from hovering directly next to it ?

**Comment by hohMiyazawa** [comment]
@Damselflies  Thanks, then I have an answer when someone asks how to install Automail there.

If it doesn't work 100%, perhaps the "Mobile Friendly mode" setting helps? If not, could you create another issue with the problems you have encountered so I can try to get them fixed?

**Comment by Damselflies** [comment]
Well I think its more of an app/ipad issue, sometimes the script doesn’t seem to load/activate with moments, generally a refresh of the page solves that, so I don’t think it’s something that has to do with the script itself really. I did put on the “mobile friendly mode”, just to make 100 sure I wouldn’t encounter any issues, if I do I’ll definitely make another issue.

**Comment by nategasm** [comment]
Yeh tooltips using the "title" attribute don't work on touchscreens (even with the mobile option turned on)

On Android you can get Firefox Nightly which lets you install Tampermonkey. You can't get extensions on the iOS version though unfortunately. 
I've tested it with this simple CSS which seems to work fine in home/user feeds and forums (touch to show). I don't have an Apple device to test this on though.
```
@media (pointer: coarse), (hover: none){
	[title]{
		position: relative;
		display: inline-flex;
		justify-content: center;
	}
	[title]:hover::after{
		content: attr(title);
		position: absolute;
		top: 90%;
		right: 0;
		color: white;
		background-color: #2b2a33;
		border: 1px solid;
		width: fit-content;
		padding: 3px;
		font-size: 1.2rem;
		font-weight: normal;
		white-space: pre;
		line-height: 1;
		z-index: 1;
	}
}
```
Feed
![Screenshot_20230113-151830313](https://user-images.githubusercontent.com/28376248/212238034-f405c1d6-9a77-474e-836b-ceda3c410285.jpg)
Forum
![Screenshot_20230113-151947781](https://user-images.githubusercontent.com/28376248/212238080-2a6fd193-45b8-447f-81cc-06a5c3273b83.jpg)

@hohMiyazawa This CSS already targets mobile devices so not sure if you want to put this in the global style or the mobile one.

**Comment by hohMiyazawa** [comment]
@nategasm Global, if it works fine. Though it should probably be limited to ``.time [title]`` to not accidentally introduce unwanted behaviours elsewhere. More title locations can be whitelisted later.

**Comment by Damselflies** [comment]
Thanks @nategasm & @hohMiyazawa , happy to report its working for iOS too, again thanks for adding this to the code !
