### ISSUE TITLE
A question about installing Automail

### ISSUE THREAD

**Issue by Deepankar2060** [hohMiyazawa/Automail#22]
I am new to this so this may be a very basic question. As following the readme file, when I run cmake, it shows me the usage of the command and when I run cmake makefile, I get the error:
`C:\Users\Name\OneDrive\Desktop\Automail-master\src>cmake makefile`
`CMake Error: The source directory "C:/Users/Name/OneDrive/Desktop/Automail-master/src/makefile" is a file, not a directory.`
I wanted to know what was causing this and how to fix it.
 Thanks for the help!

**Comment by hohMiyazawa** [comment]
1. If you just want to use the script, it's not necessary to build it from source. You can find builds [on greasyfork](https://greasyfork.org/en/scripts/370473-automail) (for userscript managers) or [as a firefox addon](https://addons.mozilla.org/en-US/firefox/addon/aniscripts/) (less frequently updated).

2. If you want to build from source, you will have to run "make", not "cmake". I think the documentation is wrong there, and I will update it.

**Comment by Deepankar2060** [comment]
oh, sorry I just read it wrong, thanks for the quick reply!
