### ISSUE TITLE
Add the possibility to use synonyms for mangas

### ISSUE THREAD

**Issue by lepetitpaco** [hohMiyazawa/Automail#227]
Sometimes, some mangas have as a main displayed name, a name that no scanlation site use. 
Instead, it's a synonym that is used on every platforms. 
Would it be possible to have the choice of selecting a synonym as an alternative  ?

**Comment by hohMiyazawa** [comment]
Can't you just set it as a synonym as a regular alias?
```/manga/30651/Nausicaä``

**Comment by lepetitpaco** [comment]
How would that work ? Would that change the displayed name site wide to Nausicaä instead of Nausicaä of the Valley of the Wind ?

**Comment by hohMiyazawa** [comment]
Yes.

**Comment by lepetitpaco** [comment]
I think I missed the feature then, where do I find that ? That would be great

**Comment by hohMiyazawa** [comment]
On the setting page (https://anilist.co/settings/apps) > Apps & Automail, scroll down below the checkboxes

![screen](https://user-images.githubusercontent.com/58218853/212766745-7fef16eb-8274-4a4c-9c8b-6b1c62566fe7.png)

**Comment by lepetitpaco** [comment]
Oh, I really missed it thank you for your help and sorry
