### ISSUE TITLE
Timestamp text overlaps with donator badge

### ISSUE THREAD

**Issue by alsoGAMER** [hohMiyazawa/Automail#234]
![Screenshot_20230119-162352_Kiwi Browser.png](https://user-images.githubusercontent.com/35269770/213482253-897e81bf-b9a5-4a5e-8b4d-c4a33cfbb780.png)

This only happens in the activity _card_ on the home feed.

**Comment by nategasm** [comment]
Seems like a more common issue for 2 column feeds due to the smaller horizontal space. Also occurs on any screen size up to 1540px wide, especially with longer custom badges.

Some CSS like this would work, but maybe not the most elegant way as longer badges may still overflow (I don't know what the character limit is on those)
```
.home .activity-entry .donator-badge{
	top: 30px;
	right: 10px;
	max-width: 75px;
}
```

**Comment by alsoGAMER** [comment]
> Is this on mobile?

yeah

**Comment by alsoGAMER** [comment]
> Seems like a more common issue for 2 column feeds due to the smaller horizontal space. Also occurs on any screen size up to 1540px wide, especially with longer custom badges.
> 
> Some CSS like this would work, but maybe not the most elegant way as longer badges may still overflow (I don't know what the character limit is on those)
> 
> ```
> .home .activity-entry .donator-badge{
> 	top: 30px;
> 	right: 10px;
> 	max-width: 75px;
> }
> ```

i'll try it later to see if fixes the issue, thank you!

**Comment by hohMiyazawa** [comment]
The two column layout was never something I have been heavily invested in. Somebody asked for it, and I said sure, since it's just some CSS.
Maybe they have a wide screen or something.

I question how much it's worth the effort to squeeze it into a mobile screen.

**Comment by hohMiyazawa** [comment]
I suggest a full redesign for mobile here.

Two columns on mobile looks like cards, so why not make it cards with big, easy to click, regions?

![redesign](https://user-images.githubusercontent.com/58218853/213571239-7310e9c5-28c5-4687-8dac-e1cbed840a40.png)

**Comment by hohMiyazawa** [comment]
First round of mild adjustments https://github.com/hohMiyazawa/Automail/commit/0768d63c9fa5a40b16a8541bcefe2424d38d8ced

**Comment by alsoGAMER** [comment]
Still happening as of version 10.4.12 and its even worse now somehow
Tested on chrome 111 emulating a Samsung s20 ultra @ 412x915 (62% zoom - fit page) in portrait mode

![image](https://user-images.githubusercontent.com/35269770/214100057-317af920-c9d6-41ef-829c-ae8405e0ddcd.png)
![image](https://user-images.githubusercontent.com/35269770/214100174-80e54dd5-cb9a-4ebb-87fb-617e04a04df1.png)

Though this doesn't happen on larger posts (videos, pics, etc)
![image](https://user-images.githubusercontent.com/35269770/214100367-b485f9dc-1938-40db-b0ee-e93bc75fa6dc.png)

**Comment by alsoGAMER** [comment]
Issue seems to have been fixed

on portrait
![portrait](https://user-images.githubusercontent.com/35269770/214101967-b23e0ea2-b3c7-45f8-bb7b-64265e411ee4.png)

on landscape
![landscape](https://user-images.githubusercontent.com/35269770/214102271-89ec5ce3-8c67-4677-999e-042cabfe8da8.png)
