### ISSUE TITLE
Improve status dots' filters

### ISSUE THREAD

**Issue by LorenzoRamalho** [hohMiyazawa/Automail#24]
While making use of the dots to filter by status I thought it would be nice if by clicking the selected filter again it'd reset.

https://github.com/hohMiyazawa/Automail/blob/9839eb034af290e4aad1b0947ae45390f1234cca/src/modules/replaceStaffRoles.js#L608-L611
Something like this could work maybe?
```javascript
if (filterSelect.value == "status:" + status.toLowerCase()) {
    filterSelect.value = "";
} else {
    filterSelect.value = "status:" + status.toLowerCase();
}
// ...plus event thingy
```

**Comment by hohMiyazawa** [comment]
Sounds like a good idea, will be implemented.

**Comment by hohMiyazawa** [comment]
Yeah, just what you posted is all that's needed.
Will be part of the next release in a couple of days.

https://github.com/hohMiyazawa/Automail/commit/ace7e4aca959d81dc8af19fca4d3f1707214744a

**Comment by LorenzoRamalho** [comment]
Found a bit of a weird behavior relating to this function.
When selecting the filter by 'planning' the other dots remain visible. Unlike the rest which hides the rest of the dots when selected.

This is me being pedantic though. But since the thread is already here, why not document it, I thought.
I'd look into fixing it, but just looking at this code makes my head go 💥. But honestly, this is totally unimportant.

![filter-dots-behaviour](https://user-images.githubusercontent.com/4308861/80928220-e6be1e80-8d79-11ea-99e6-bf64f8248856.gif)

**Comment by hohMiyazawa** [comment]
@LorenzoRamalho This happens because the stats are not updated when there's no time watched or chapters/volumes read.

Incidentally, planning would have no stats whatsoever, which is less useful than just showing the stats for everything.
So that's by-design.
