### ISSUE TITLE
Twitter embeds don't load on Firefox

### ISSUE THREAD

**Issue by 466frfx** [hohMiyazawa/Automail#250]
("Embed linked tweets" option enabled, of course)

It just stays like this forever:
![image](https://user-images.githubusercontent.com/17676761/217671147-93df0e4f-6b12-4e66-abee-f9e585c9e4b4.png)

Tried with the userscript installed with FireMonkey, then with Greasemonkey. I also tried disabling enhanced tracking protection and uBlock Origin.

Console output (I'm not sure there's anything here related to the issue though):
![image](https://user-images.githubusercontent.com/17676761/217672223-3e72ab9d-5460-40ea-8645-d460a8bae576.png)

**Comment by kazzarin** [comment]
It should work just by disabling "Enhanced Tracking Protection" just for Anilist as the embedding script gets blocked by FF's social media tracker list. Also, Twitter being down earlier today could be a factor.
