### ISSUE TITLE
Additional stats don't load on own profile in Firefox, most of the time

### ISSUE THREAD

**Issue by 466frfx** [hohMiyazawa/Automail#251]
Previously mentioned in #49 and supposedly fixed in #93 but most of the time it doesn't work for me on Firefox, with the userscript installed with Greasemonkey. (and if installed with FireMonkey, the feature doesn't work on _any_ profiles)

Seems to look a little different from #49's description; instead of loading forever on the "More Stats" section it just says nothing where the stats ordinarily would be:
![image](https://user-images.githubusercontent.com/17676761/217674117-086daca2-aa0c-48f5-96c9-f654da11d138.png)
"Genre & Tags" does load forever, though:
![image](https://user-images.githubusercontent.com/17676761/217674210-2c367f5f-5939-432e-9c87-a2edd7837d29.png)

And of course, another difference from #49 is that it sometimes works? When I first installed Greasemonkey to see if it would work, it loaded fine, and then didn't work at all for subsequent attempts, except for one time I alt-tabbed into it (don't remember if I refreshed too?) and it worked when I clicked on the sections again.

For the second working attempt, I remember seeing `Multiple copies of the script running? Shutting down this instance` in the console. Not sure if it's related or if it's just because I had multiple AniList tabs open, or because I have multiple userscript managers installed (with the userscript disabled in FireMonkey while testing with Greasemonkey), or something else.

Persistent storage does seem to be enabled:
![image](https://user-images.githubusercontent.com/17676761/217675103-96b57119-fea1-48e9-a611-7e5d5eb5f7a1.png)
and if I look at the storage section of devtools, there is Automail related stuff in session storage, local storage and Indexed DB, so I'm pretty sure that's working fine.

Console output:
![image](https://user-images.githubusercontent.com/17676761/217676349-9ca12d15-6072-4efd-985a-9c8507dae745.png)
The last two lines seem to be directly related to the issue, with the supposedly problematic code (with line numbers added and indents removed for readability) being:
```js
21506	if(entry.isCustomList){
21507		entry.listLocations = [mediaList.name] // Error on this line
21508	}
21509	else{
21510		entry.listLocations = [] // Error on this line
21511	}
````

**Comment by hohMiyazawa** [comment]
This looks messy, but it seems like this is an issue with the caching strategy for own stats pages.
