### ISSUE TITLE
april 30 2020 site update

### ISSUE THREAD

**Issue by hohMiyazawa** [hohMiyazawa/Automail#26]
I know this breaks some stuff.

Report them here.

**Comment by StilesClover** [comment]
The right sided vetical navbar got some problems

Profile picture: https://i.ibb.co/cgZZJM5/Unbenannt.png

Browser: https://i.ibb.co/kX6G0LF/2.png

The profile tab is still fine

**Comment by hohMiyazawa** [comment]
@StilesClover Do you still have this issue with v9.50?

**Comment by StilesClover** [comment]
Is fixed :D Thx for the fast fix <3

**Comment by hohMiyazawa** [comment]
v9.50 fixes:
- Broken vertical nav and vertical right-side nav mostly fixed.
- Added an option to disable some UI animations.
- Fixed missing twitter logo.
- Fixed right-side overflow of the browse section
- Adjusted colour of the submenu to match the other dropdowns.

**Comment by hohMiyazawa** [comment]
v9.51 fixes:
- Fixed spelling error in the "Kaguya-sama wa Kokurasetai" alias, and added an alias for season 2.
- Added back the extra episode, chapter and volume sorting options to browse.
- The "browse" entry in the vertical navbar now has less wrong visual hover effects.
- Added an option for a slimmer navbar.
- Implemented the new orange colour of the "meh" smily rating, for consistency.
- Updated description of the "compact browse mode" (currently doesn't do much).
- Removed the old list view toggle for browse as it isn't needed anymore.
- "interesting recs" no longer a newly added module.
- "right side navbar" no longer a newly added module.

**Comment by hohMiyazawa** [comment]
v9.52 fixes:
- Slight blue highlight for current selected list mode in browse.
- Triangular range handles, for better accuracy.
- Brought back small prefix numbers, for the list view mode in browse.
- Removed old useless compact mode code.
- Added some new compact mode stubs.
- Added a few more animations to the annoying animation remover.
- Added an option to use the old dark mode colours.

**Comment by Kreyren** [comment]
Custom CSS does not seem to work and seems disabled in settings, forcing it seems to be able to render the website though.

See https://anilist.co/user/kreyren/

**Comment by hohMiyazawa** [comment]
@Kreyren Your profile appears to have custom CSS, so I don't see what the problem is.

**Comment by Kreyren** [comment]
@hohMiyazawa I don't have the customCSS in settings:
![image](https://user-images.githubusercontent.com/11302521/81003132-a8dcfb00-8e4a-11ea-97f3-4b453965849a.png)

The current customCSS has been parsed manually.

**Comment by hohMiyazawa** [comment]
That's odd, shows up fine on my end.

A couple of things to test:
- Anything printed to the console when visiting that page?
- If you're using an addblocker, is the section still gone if you turn it off for a moment?

**Comment by Kreyren** [comment]
> Anything printed to the console when visiting that page?

```
Request to access cookie or storage on “https://fonts.googleapis.com/css?family=Roboto:300,400,500,700” was blocked because we are blocking all storage access requests.
account
Request to access cookie or storage on “https://fonts.googleapis.com/css?family=Overpass:400,600,700,800” was blocked because we are blocking all storage access requests.
account
Request to access cookie or storage on “https://www.gstatic.com/recaptcha/releases/wk6lx42JIeYmEAQSHndnyT8Q/recaptcha__en.js” was blocked because we are blocking all storage access requests.
account
Request to access cookie or storage on “https://linx.li/s/ph6s6jti.png” was blocked because we are blocking all storage access requests.
account
Cache enabled: v14 main.f4809ecb.js:1:29572
Automail 9.50 automail.js:12013:9
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features! account
Loading failed for the <script> with source “https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js”. home:1:1
Unhandled promise rejection Error: "//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"
    onerror https://anilist.co/js/chunk-vendors.f83285e1.js:21
chunk-vendors.f83285e1.js:21:31691
Request to access cookie or storage on “https://media.giphy.com/media/Th3uESliZZxf7EDInp/giphy.gif” was blocked because we are blocking all storage access requests.
home
Request to access cookie or storage on “https://linx.li/s/l5gb5kly.png” was blocked because we are blocking all storage access requests.
home
Request to access cookie or storage on “https://linx.li/s/7a466pph.png” was blocked because we are blocking all storage access requests.
home
Request to access cookie or storage on “https://linx.li/s/325jtmgz.png” was blocked because we are blocking all storage access requests.
home
Request to access cookie or storage on “https://linx.li/s/mwrgeke6.png” was blocked because we are blocking all storage access requests.
home
Request to access cookie or storage on “https://linx.li/s/mdasass9.png” was blocked because we are blocking all storage access requests.
home
Request to access cookie or storage on “https://media.giphy.com/media/KHJuiXvxq7TPrEvBNr/giphy.gif” was blocked because we are blocking all storage access requests.
home
Request to access cookie or storage on “https://media.giphy.com/media/RhAthlQhbOtgz0nEcj/giphy.gif” was blocked because we are blocking all storage access requests.
home
Request to access cookie or storage on “https://media.giphy.com/media/U4A7kV7EQmLtjZi1Wd/giphy.gif” was blocked because we are blocking all storage access requests.
home
Request to access cookie or storage on “https://media.giphy.com/media/Yo8rZHm0sszA4DmKNk/giphy.gif” was blocked because we are blocking all storage access requests.
home
Request to access cookie or storage on “https://media.giphy.com/media/XZUHxvQC22uLvnThHe/giphy.gif” was blocked because we are blocking all storage access requests.
home
Request to access cookie or storage on “https://media.giphy.com/media/jRkFFmcQ5SnfCdVPML/giphy.gif” was blocked because we are blocking all storage access requests.
home
Request to access cookie or storage on “https://media.giphy.com/media/XDuuaXRD5RBYF85USI/giphy.gif” was blocked because we are blocking all storage access requests.
home
Request to access cookie or storage on “https://media.giphy.com/media/eLw8kNs2xCUGner8So/giphy.gif” was blocked because we are blocking all storage access requests.
home
Request to access cookie or storage on “https://media.giphy.com/media/SsCSzTlIc0LWtC7Upv/giphy.gif” was blocked because we are blocking all storage access requests.
home
Request to access cookie or storage on “https://i.gifer.com/TcgK.gif” was blocked because we are blocking all storage access requests.
kreyren
Request to access cookie or storage on “https://media1.tenor.com/images/794d7b531cc54044af8473ee1f8e84eb/tenor.gif?itemid=16226830” was blocked because we are blocking all storage access requests.
kreyren
Request to access cookie or storage on “https://i.imgur.com/9URgfnP.png” was blocked because we are blocking all storage access requests.
kreyren
Request to access cookie or storage on “https://i.imgur.com/Woaey3a.png” was blocked because we are blocking all storage access requests.
kreyren
TypeError: "t.path is undefined"
    onClick https://anilist.co/js/main.f4809ecb.js:1
    ne https://anilist.co/js/chunk-vendors.f83285e1.js:17
    n https://anilist.co/js/chunk-vendors.f83285e1.js:17
    _wrapper https://anilist.co/js/chunk-vendors.f83285e1.js:17
chunk-vendors.f83285e1.js:17:12021
    ie https://anilist.co/js/chunk-vendors.f83285e1.js:17
    re https://anilist.co/js/chunk-vendors.f83285e1.js:17
    ee https://anilist.co/js/chunk-vendors.f83285e1.js:17
    ne https://anilist.co/js/chunk-vendors.f83285e1.js:17
    n https://anilist.co/js/chunk-vendors.f83285e1.js:17
    _wrapper https://anilist.co/js/chunk-vendors.f83285e1.js:17
TypeError: "t.path is undefined"
    onClick https://anilist.co/js/main.f4809ecb.js:1
    ne https://anilist.co/js/chunk-vendors.f83285e1.js:17
    n https://anilist.co/js/chunk-vendors.f83285e1.js:17
    _wrapper https://anilist.co/js/chunk-vendors.f83285e1.js:17
chunk-vendors.f83285e1.js:17:12021
    ie https://anilist.co/js/chunk-vendors.f83285e1.js:17
    re https://anilist.co/js/chunk-vendors.f83285e1.js:17
    ee https://anilist.co/js/chunk-vendors.f83285e1.js:17
    ne https://anilist.co/js/chunk-vendors.f83285e1.js:17
    n https://anilist.co/js/chunk-vendors.f83285e1.js:17
    _wrapper https://anilist.co/js/chunk-vendors.f83285e1.js:17
```

> If you're using an adblocker, is the section still gone if you turn it off for a moment?

Using nanoblocker, same issue with it disabled

---

FWIW i am blocking trackers, maybe that affects it?:
![image](https://user-images.githubusercontent.com/11302521/81004589-ea6ea580-8e4c-11ea-88d6-dadc69eb9468.png)

![image](https://user-images.githubusercontent.com/11302521/81004659-07a37400-8e4d-11ea-9a88-2881f845708a.png)

**Comment by hohMiyazawa** [comment]
Nothing in that console trace looks unusual.
The only thing I can see is that you are running v9.50 of Automail, and not v9.52 which is the current version.

**Comment by hohMiyazawa** [comment]
Will try to bring up the relevant portion of the code...

**Comment by hohMiyazawa** [comment]
Wait, are you signed in with the script? (check if stuff in the "login" tab is greyed out)

The script can't save CSS data to your profile without permissions.

**Comment by Kreyren** [comment]
Seems that i am not logged in based on available info:
![image](https://user-images.githubusercontent.com/11302521/81006183-5e11b200-8e4f-11ea-9e32-3280540d16b4.png)

`Sign in with the script` button just redirects to the homepage where i gave it the permission inb4

**Comment by Kreyren** [comment]
> you are running v9.50 of Automail, and not v9.52 which is the current version.

updating

**Comment by hohMiyazawa** [comment]
If you give it permission after clicking the link, but the "login" stuff stays greyed out, something's wrong with the login system.

**Comment by Kreyren** [comment]
> If you give it permission after clicking the link, but the "login" stuff stays greyed out, something's wrong with the login system.

It doesn't ask for the permission where i already grant it the permission before.

Redirects to https://anilist.co/home#access_token=REDACTED_TOKEN&token_type=Bearer&expires_in=31536000

**Comment by Kreyren** [comment]
So i assume that in https://github.com/hohMiyazawa/Automail/issues/26#issuecomment-623657186 the `useScripts.accessToken` returns false?

**Comment by Kreyren** [comment]
also FWIW this does not stay checked:
![image](https://user-images.githubusercontent.com/11302521/81006978-b09f9e00-8e50-11ea-8c67-137a2e518f91.png)

**Comment by Kreyren** [comment]
Assuming https://github.com/hohMiyazawa/Automail/blob/bc3ef2ea877862ccddd87ec62a5a885e442f096f/src/modules/settingsPage.js#L29 -> The `useScripts.accessToken ` return false is confirmed

**Comment by hohMiyazawa** [comment]
Yeah, that's probably it. You are not getting an access token for some reason

To test that definitely:
- Go to the script setting
- Click the "script" tab
- Enable "Enable an API for other scripts to control automail".
- Refresh the page
- In the console, paste "document.automailAPI.settings.accessToken"

You should be getting a long string of gibberish if you have an access token. DO NOT POST IT HERE.

**Comment by Kreyren** [comment]
Disabling anti-tracking measures seems to make it work:

![image](https://user-images.githubusercontent.com/11302521/81007496-9adea880-8e51-11ea-9e16-2b93fe105c67.png)

**Comment by hohMiyazawa** [comment]
Do normal (not login tab) settings stay checked after a refresh?

If not, some of your addons or blockers are preventing Anilist from storing your settings data (which includes the access token).

For privacy reasons, your settings are stored locally on your machine and not on some central server. If you disable all local storage, Automail can't save your preferred settings.

**Comment by Kreyren** [comment]
> To test that definitely:...

```
Automail 9.50 automail.js:12013:9
allow pasting
SyntaxError: unexpected token: identifier
debugger eval code:1:6
document.automailAPI.settings.accessToken
TypeError: document.automailAPI is undefineddebugger eval code:1:1
    <anonymous> debugger eval code:1
```

Note that requested option is greyed-out
![image](https://user-images.githubusercontent.com/11302521/81008084-98c91980-8e52-11ea-99a2-633639d1ed6f.png)

**Comment by Kreyren** [comment]
> Do normal (not login tab) settings stay checked after a refresh?

non-greyed out options persists. 

> For privacy reasons, your settings are stored locally on your machine and not on some central server. If you disable all local storage, Automail can't save your preferred settings.

Permission `Store Data In Persist Storage` is allowed for anilist.co

**Comment by Kreyren** [comment]
@hohMiyazawa Seems that i had cookies set to allow per session which prevented Automail from storing the access token. I now set the cookies for anilist.co as Allowed which seems to fix the issue.

**Comment by hohMiyazawa** [comment]
Okay, that's solved then.

To wrap it up, do you want some behaviour to change in the cases where cookie(really localStorage) access is set to per session?

**Comment by Kreyren** [comment]
> To wrap it up, do you want some behaviour to change in the cases where cookie(really localStorage) access is set to per session?

Recommends making a warning about this somewhere so that it's not surprising for the end-user like me to encounter this behavior.

Additionally i am not sure how i feel about allowing permanent cookies to anilist.co assuming the amount of trackers used so ideally i would like it to work with non-persistent cookies, but i am not sure what are the implications for automail assuming that it would probably require to re-authentificate after each request which would make it less efficient?

**Comment by hohMiyazawa** [comment]
To make it clear, it's impossible (by design) for any script to detect if cookies are deleted after each session.

What I imagine is perhaps a setting that does the asking-for-an-access-token thing automatically the first time Anilist is opening in a new browser session.

The next best thing for very privacy-conscious people in the mean time is to patch Automail by copy-pasing your access token into the default settings in the source code.

Note that Automail is designed to still *mostly* work, even without persistent storage.

**Comment by Kreyren** [comment]
> What I imagine is perhaps a setting that does the asking-for-an-access-token thing automatically the first time Anilist is opening in a new browser session.

Seems sane to me, but i would recommend a peer-review in case there is a better option that may not be known to us. 

### Some theories
- In theory and assuming that automail is expected to work without persistent storage i would think that we might be able to store this in-code similar to proposed patch, but that would be probably weird hack way..
- What about custom domain that would store those that can be allowed to store this data possibly on github pages assuming the data encrypted and decrypted by the end-user?
- Some configuration in web-browser that would allow specific cookies to persist?
  - Some option in web-browser to store these somewhere safe? Assuming it being confidential access token i would think that reading this from the local system would be better?
- Requesting anilist.co to store these tokens somehow? Not sure how secure that would be though.
- Optional option to store this in persistent storage?

> The next best thing for very privacy-conscious people in the mean time is to patch Automail by copy-pasing your access token into the default settings in the source code.

Some documentation for this would be nice ^-^

**Comment by hohMiyazawa** [comment]
> Some documentation for this would be nice ^-^, but from my research on fingerprinting some fingerprinters might be able to read these?

Will drop a text file in the doc folder about how to patch default settings in.source

> What about custom domain that would store those that can be allowed to store this data possibly on github pages assuming the data encrypted and decrypted by the end-user?

This is against the current design philosophy of the project, which is to not rely on server services. The failure potential of this approach, leaking thousands of access tokens, is also much greater than the inconvenience it removes.

> Some configuration in web-browser that would allow specific cookies to persist?

I'm not aware of any APIs that allow this. Automail has no greater permissions than other scripts running on the anilist.co domain.

> Requesting anilist.co to store these tokens somehow? Not sure how secure that would be though.

I'm pretty sure Anilist will not be willing to provide such a service to third-party scripts.

**Comment by hohMiyazawa** [comment]
It would actually be possible to make custom default settings impossible to fingerprint, if the script makes to attempt to save them to storage.
They are not globally available in the page scope.

**Comment by hohMiyazawa** [comment]
v9.53 fixes:

- Theme switcher on studio pages is back up.
- Fixed missing status dot in browse for aliased titles

**Comment by SingerCo** [comment]
Hi,

On the newly redesigned Studios page on AL ([example](https://anilist.co/studio/44/Shaft)), when using Automail the list status icons (green dot for completed, red dot for dropped, blue dot for watching) are currently hidden. 

The way I've found to get them to show up again is to comment out the following two rules located at line 2913 in the script:

`/*
.search-page-unscoped.cardView .list-status,
.studio-page-unscoped.cardView .list-status{
	transform: translate(-18px,-18px);
}
*/`
`/*
.search-page-unscoped:not(.listView) .list-status,
.studio-page-unscoped:not(.listView) .list-status{
	transform: translate(-20px,-20px);
}
*/`

Something that can be relatively easily fixed on the user end but wanted to bring it up for a global fix when possible.

Thanks!

**Comment by hohMiyazawa** [comment]
@SingerCo Moved some code around to make this (and several related things) work properly

https://github.com/hohMiyazawa/Automail/commit/288491a7e8b07bb0bbb6a755bb126a082743fb46

**Comment by hohMiyazawa** [comment]
The April 30 changes are no longer relevant for lumping releated issues together.
Closed.
