### ISSUE TITLE
"For You" Recommendations tab no longer loading any results

### ISSUE THREAD

**Issue by nukirisame** [hohMiyazawa/Automail#272]
Using Firefox

**Comment by hohMiyazawa** [comment]
Hm, works on my end.

- This module requires the "sign in with the script" thing to load list data. Is the script still authorised?
- Any errors in the console? (right click > inspect element > console)

**Comment by nukirisame** [comment]
There are two errors in the console: "TypeError: node.mediaRecommendation is null" and "Uncaught (in promise) TypeError: data is null".

**Comment by hohMiyazawa** [comment]
Ah, interesting. Probably some bad data. I should probably add some more error handling that just skips those, and displays the rest instead of just crashing.

**Comment by hohMiyazawa** [comment]
@nukirisame Does the update (v10.4.20) work for you?

**Comment by nukirisame** [comment]
It does! Thank you for such a speedy response.
