### ISSUE TITLE
Error spam (Firefox, potentially slowing down the page?)

### ISSUE THREAD

**Issue by Kex1016** [hohMiyazawa/Automail#278]
I'm not sure how to title this. I'm using Firefox 115.0.1 on Arch Linux, but this has been a problem for earlier versions too.

After AniList loads in, the script works fine without any errors, but when I go to my profile's overview page (https://anilist.co/user/cakes/), it starts spitting out these errors:
![image](https://github.com/hohMiyazawa/Automail/assets/28629874/22040153-a69f-4e40-a36a-a547e9eeafed)
I tried only enabling the script and nothing else, and I am pretty sure it's caused by Automail, but I don't know if it's explicitly the script's fault. I also couldn't really find where it's coming from because the debugger doesn't say anything about it. It slows down the page after a while, of course fixed with a reload every time.

**Comment by hohMiyazawa** [comment]
Hm. Your browser is saying that the BroadCastchannel API is available, but then it doesn't work.

Not a big deal, it's only used to avoid having different browser tab request the exact same data from the Anilist API, saving a couple of API calls once in a while.

I've changed the default to stop trying to use it if it fails for some reason.
