### ISSUE TITLE
monthly stats does not count last episodes

### ISSUE THREAD

**Issue by z00rat** [hohMiyazawa/Automail#289]
so, i just ended rewatching **Cyberpunk: Edgerunners**.
and it has 10 ONA episodes.
but monthly stats only showing 9. 

i guess anilist logs like **"Rewatched episode 6 - 9 of Cyberpunk: Edgerunners"** then **"Rewatched Cyberpunk: Edgerunners"**.
they never says **1-10** but **1-9** then **finished**.

**Comment by z00rat** [comment]
looks like https://github.com/hohMiyazawa/Automail/blob/35a1b4acc4c2f2b87e590082fee6c39950e0cc51/src/queries/seasonalStats.js#L84-L88
this code supposed to do this, but i'm kinda confused ...

**Comment by hohMiyazawa** [comment]
The code is older than the current rewatch/reread completion statuses. I will update it.

**Comment by hohMiyazawa** [comment]
Probably fixed.

**Comment by z00rat** [comment]
awesome,
it works perfectly now.
