### ISSUE TITLE
Add HTML title attribute to staff roles

### ISSUE THREAD

**Issue by LorenzoRamalho** [hohMiyazawa/Automail#29]
Have come across this sometimes.
![](https://i.imgur.com/6IFVcvw.png)
First idea that comes to mind would be to add a title= attribute.
What do you think?

https://github.com/hohMiyazawa/Automail/blob/e9288244c4289a0dc8d789eca4302f91b05e4bcd/src/modules/replaceStaffRoles.js#L324-L332
```javascript
+++
role.title = role.textContent;
```

**Comment by hohMiyazawa** [comment]
Yeah.
Should probably be joined by newlines though.

**Comment by hohMiyazawa** [comment]
https://github.com/hohMiyazawa/Automail/commit/5c349d3afc3917378e2c89a2b7e98e1867c46dd7

- Added title attribute.
- Made a better heuristic to place important credits first.
- Made the credit list scrollable on hover.
