### ISSUE TITLE
Alternative list preview ERROR

### ISSUE THREAD

**Issue by miguelreinalde** [hohMiyazawa/Automail#290]
My "manga in progress" section doesn't show up for several days. Any idea of what's causing this problem?
Appreciate the help.

**Comment by hohMiyazawa** [comment]
Screenshot? Anything printed to the console?

**Comment by miguelreinalde** [comment]
Thanks for the fast answer!!


![imagem_2023-12-30_211203992](https://github.com/hohMiyazawa/Automail/assets/155258245/5127aec9-a73e-4019-a2e2-f5878d507a0a)


![imagem_2023-12-30_211130423](https://github.com/hohMiyazawa/Automail/assets/155258245/33588540-e196-4aaa-ac81-75e196425a65)

**Comment by hohMiyazawa** [comment]
Hm. that's weird. I'm not seeing anything obviously wrong.

**Comment by miguelreinalde** [comment]
I tried with other browsers, I even tried to clear the cookies of anilist. But still the same.

**Comment by miguelreinalde** [comment]
Already fixed it, it wasn't a error. When I had 4 anime in watching and 4 manga in reading it worked. Can you say why that works like that? Because I would prefer to not have that limitation.
