### ISSUE TITLE
Status Icons Vanished on Redesigned Studios Page

### ISSUE THREAD

**Issue by SingerCo** [hohMiyazawa/Automail#30]
Hi,

On the newly redesigned Studios page on AL ([example](https://anilist.co/studio/44/Shaft)), when using Automail the list status icons (green dot for completed, red dot for dropped, blue dot for watching) are currently hidden. 

The way I've found to get them to show up again is to comment out the following two rules located at line 2913 in the script:

`/*
.search-page-unscoped.cardView .list-status,
.studio-page-unscoped.cardView .list-status{
	transform: translate(-18px,-18px);
}
*/`
`/*
.search-page-unscoped:not(.listView) .list-status,
.studio-page-unscoped:not(.listView) .list-status{
	transform: translate(-20px,-20px);
}
*/`

Something that can be relatively easily fixed on the user end but wanted to bring it up for a global fix when possible.

Thanks!

**Comment by SingerCo** [comment]
Closed, realized this belongs in the April 30 update thread. My bad.

**Comment by hohMiyazawa** [comment]
For the record, there's nothing wrong with starting separate issues even if there's already a thread for related problems.
