### ISSUE TITLE
"Airing" and "In Progress" Tab Break When Expanded.

### ISSUE THREAD

**Issue by HassanSan525** [hohMiyazawa/Automail#301]
Whenever the airing and in progress tabs are expanded their is a void of useless space created on the left side of the page until the activity feed. This is a issue created only when I use automail and gets fixed when I disable it.
![image](https://github.com/hohMiyazawa/Automail/assets/123470321/f7ed703c-74be-4eb3-8234-5a761d050c08)

**Comment by hohMiyazawa** [comment]
There's so much different stuff that affects the preview layout, so I would need your settings to see exactly what modules you are using.

Go to "https://anilist.co/settings/apps", scroll to the bottom, and click the button to export your settings. Then upload the file here.

Not all modules support the expanded view though.

**Comment by HassanSan525** [comment]
[](url)
[Uploading Automail_settings_HassanSan.json…]()

**Comment by HassanSan525** [comment]
[Automail_settings_HassanSan.json](https://github.com/user-attachments/files/16039525/Automail_settings_HassanSan.json)

**Comment by HassanSan525** [comment]
So there's no way?
