### ISSUE TITLE
Selecting the "Following" tab doesn't work many times, the feed defaults to "Global" tab after loading for a while

### ISSUE THREAD

**Issue by Lagazah** [hohMiyazawa/Automail#304]
https://github.com/user-attachments/assets/cc2e67f3-80d4-4173-80e5-049177cab3b3

**Comment by Lagazah** [comment]
Been having this for a while (like 1 month), sometimes it "fixes" itself but some other times it just stays like that for a while

**Comment by hohMiyazawa** [comment]
Unrelated to the script.

Anilist is having problems, and no devs really to fix stuff at the moment.

**Comment by Lagazah** [comment]
oh, okok
