### ISSUE TITLE
AniList borked HTML comments

### ISSUE THREAD

**Issue by Kex1016** [hohMiyazawa/Automail#33]
HTML comments now get parsed out of anything which includes bios too, so it pretty much breaks the custom CSS module.
Me and @DatLycan are trying to get a RegEx to work using markdown's comments that look like this:
```
[comment]: # "(<comment text goes here>)"
```

**Comment by hohMiyazawa** [comment]
Affected modules:
 - CustomCSS
 - Profile backgrounds

**Comment by hohMiyazawa** [comment]
An "invisible" markdown replacement is needed to continue these modules.

Possible fallbacks if invisible markdown is not possible:
 - Storing data in link URLs.
 - Storing data in spoiler sections.

**Comment by hohMiyazawa** [comment]
Affected files:
- settingsPage.js
- profileBackground.js
- addCustomCSS.js

**Comment by hohMiyazawa** [comment]
What about just using a tag?
<text here>
Of course, it would have to be base64 encoded

**Comment by hohMiyazawa** [comment]
I have not found a usable way to use markdown comments yet.

**Comment by hohMiyazawa** [comment]
Patch written:
https://github.com/hohMiyazawa/Automail/commit/50e6267712881a2af6b2aabbff59efeed9eac2b4

**Comment by hohMiyazawa** [comment]
HTML comments replaced by a fake HTML tag consisting of base64 encoded profile JSON, prefixed by "json".
Published as v9.70

Please reopen this if there are issues with it.

**Comment by Kex1016** [comment]
I don't think it gets parsed right
https://anilist.co/user/Kex1016/
![image](https://user-images.githubusercontent.com/28629874/82609837-95a58b80-9bbd-11ea-9a2f-7d0db6bd3871.png)

**Comment by hohMiyazawa** [comment]
Looks like long tags are not hidden.
Some other way is needed then.

**Comment by hohMiyazawa** [comment]
Are zero-length links still allowed?

**Comment by Kex1016** [comment]
Yes, they are

**Comment by hohMiyazawa** [comment]
Well then, just changed the delimeters
https://github.com/hohMiyazawa/Automail/commit/b99050a46fb26aa3ae28b0159b1c3f1b059a1e28

**Comment by DatLycan** [comment]
Well damn! This one works just as it should work. 
Thank you for the quick response and pushes hoh!

**Comment by hohMiyazawa** [comment]
Going to bed then.
Closing this tomorrow if there aren't any problems.

If you have contact on some platform with people that would like to now, tell them to:
1. Make a copy their CSS
2. Upgrade to v9.71
3. Add the CSS again

**Comment by Kex1016** [comment]
It works! Thanks for the fast fix!

**Comment by hohMiyazawa** [comment]
Possible future fallback: Anilist currently doesn't strip data attributes.
