### ISSUE TITLE
Like previews

### ISSUE THREAD

**Issue by emrexemre** [hohMiyazawa/Automail#39]
![Screenshot_2020-09-06_18-58-59](https://user-images.githubusercontent.com/38049110/92329953-cbd72000-f073-11ea-92a3-4acf76148444.png)
Can we have an option to close these? If there's already and i missed it, so sorry.

**Comment by hohMiyazawa** [comment]
What am I looking at?
What is the thing you want to close?

**Comment by emrexemre** [comment]
those profile pictures

**Comment by hohMiyazawa** [comment]
What about them? They are part of native Anilist.
The appear on hover over the likes, and disappear when you move away.

**Comment by emrexemre** [comment]
It would be nice if they never show up but if it's not possible, it's totally okay

**Comment by hohMiyazawa** [comment]
Ah, a way to disable them. That should be pretty easy (why though?)

**Comment by emrexemre** [comment]
I'm using an old device so I thought if they don't show up, the lag would be less

**Comment by hohMiyazawa** [comment]
Even if I add code to remove them, the lag will probably not be reduced by any significant amount.

**Comment by emrexemre** [comment]
Oh, is that so :/ Then there's not much use for this feature.

**Comment by emrexemre** [comment]
That was what I needed. Thank you.
