### ISSUE TITLE
Copy anime's start and finish date to your list

### ISSUE THREAD

**Issue by ghost** [hohMiyazawa/Automail#42]
I joined AL many years after I started watching anime. There are a lot of anime that I watched while it was airing but those don't have dates on them. Would it be possible for you to implement a function that lists all anime without dates. Then it let's you choose the anime one by one or all of them and copies the start and finish date on the anime's media page to your list.

**Comment by hohMiyazawa** [comment]
On your stats page, under "more stats", and "various statistics" on that page, there's a query called "fix your dating mess".
At present, it doesn't have an option for doing what you suggest.

However, I think I can add something like that there. Thinking perhaps a button saying "copy missing dates from media" attached to each item in the list.

**Comment by hohMiyazawa** [comment]
Not doing this. Too unsafe
