### ISSUE TITLE
Bio bug in Opera Gx

### ISSUE THREAD

**Issue by StilesClover** [hohMiyazawa/Automail#43]
Since today the pictures in my (and everyone elses) bio are extremly large. I tested it and if i deactivate automail everything is normal again. After that i tested it with the google chrome browser and there everything is normal even with the script. So i don't know if its a bug from my opera gx browser or the automail script. 

[With automail](https://i.ibb.co/4Z9Cq4D/Unbenannt.png)
[Without automail](https://i.ibb.co/cDDMv8d/2.png)

And i use img24% for the picture size but nothing changes if i use img220.

**Comment by hohMiyazawa** [comment]
Was an issue with with v9.96.7, online for a few hours during October 27.
Recommended fix is upgradexing to v9.96.8
