### ISSUE TITLE
"Most liked status posts" query crashes browser.

### ISSUE THREAD

**Issue by DatLycan** [hohMiyazawa/Automail#44]
As the title suggests the _**Most liked status posts**_ query at the bottom of ones _**More stats**_ page crashes the browser. 
_It seems like the `for loop` from line `22164 - 22166` of the script is running indefinitely:_ 
```
for(var i=2;i<=data.data.Page.pageInfo.lastPage;i++){
	generalAPIcall(query,{userId: userId,page: i},addNewUserData);
};
```
It would be great if you could look into this issue.

Thank you in advance!
&nbsp;
> - _Browser: **Brave (chromium-based)**_
> - _Script manager: **Tampermonkey**_
> - _Version: **9.97.1**_

**Comment by hohMiyazawa** [comment]
This is likely an upstream bug, as the Anilist API often reports incorrect page numbers these days. "lastPage" is no longer reliable.
This needs a script side workaround, most likely just looping until it receives a blank page.

**Comment by hohMiyazawa** [comment]
Workaround added in v9.97.2, which prevents the crash but limits the query to the most recent 2500 status posts. (sufficient for most users).
