### ISSUE TITLE
Looking for Slick Boy D, userstyle developer, to talk about a new project

### ISSUE THREAD

**Issue by KaKi87** [hohMiyazawa/Automail#45]
Hello,

*Slick Boy D* is a userscript developer (https://33kk.github.io/uso-archive/?page=3&sort=updated&style=162817), and he mentioned in his project's description that there is compatibility between his userstyle and your userscript on the anilist.co website.

As I'm planning to create a new userstyles sharing platform to replace userstyles.org, I would like to contact him so I could get relevant feedback from userstyles developers in order to make a platform that suits their needs.

Thanks

**Comment by hohMiyazawa** [comment]
Slick Boy D goes by [Erwin](https://anilist.co/user/erwin/) on Anilist. His userstyle is a fork of an early CSS-only version of Automail.
Compatibility is kept by some communication to give Automail widgets classes and ids that are possible to target from a third-party userstyle.

I moved away from userstyles.org when the platform went south, and currently Greasyfork meets all my requirements as a developer for userstyles and scripts.

**Comment by KaKi87** [comment]
Thanks, but I don't use the website itself.

I'm only looking for feedback from userstyles developers so I can design proper specs to create a new sharing platform.

userstyles.org's issues are the reson why I'm motivated for this project.

GreasyFork is indeed a good enough platform for userscripts, but how about userstyles ?
Redditors say GreasyFork isn't suitable for publishing userstyles :
> Greasyfork. The Forum is filled with Chinese/Russian posts because there's no separation between languages and categories.
There are no CSS previews on the website, it makes it practically impossible to find new styles. The search doesn't work either.

([Source](https://old.reddit.com/r/userstyles/comments/hqy7w7/stylus_will_have_to_change_its_provider_website/))

What do you think ?
What does Erwin think ?

Thanks.

**Comment by hohMiyazawa** [comment]
I would never use a style/script site directly to browse for new things anyway, so browse being broken on greasyfork means nothing to me.

If you want to talk to talk to Erwin, I recommend you contact him on a platform he is active on. He's not here.

**Comment by KaKi87** [comment]
Wouldn't you use the platform to search userstyles for a specific website, like userstyles.org does so slowly ?

Besides domain-specific forums, do you know where can I find him ? Preferably e-mail, Discord, or Reddit ? Thanks

**Comment by hohMiyazawa** [comment]
1) No.
2) No.
