### ISSUE TITLE
Anime status in Recommendations not loading on second page

### ISSUE THREAD

**Issue by Koopzington** [hohMiyazawa/Automail#46]
Howdy hoh!

While i was planning my December monthly i've checked [Cowboy Bebop](https://anilist.co/anime/1/Cowboy-Bebop/)'s recommendations and noticed after clicking on "View all 50 recommendations" and scrolling down to trigger loading the second page of recommendations that the status indicators are not shown on the new entries.

https://i.imgur.com/mBq9qX3.png
https://i.imgur.com/tdYrD5y.png

You might have that on your radar already but i thought i'd let you know.

Keep up the good work!
Koopz

**Comment by hohMiyazawa** [comment]
Yeah, this is just a case of the initial code being very simple, not having any way to detect more entries loading. Does 90% of what's required for half the work.

Adding a check will fix this.

**Comment by hohMiyazawa** [comment]
Now pulls a second page when required. (not a true N-page solution, but good enough).
