### ISSUE TITLE
Site breaks after switching anime/manga pages

### ISSUE THREAD

**Issue by blueYOSHI9000** [hohMiyazawa/Automail#47]
**Description**
Sometimes when clicking on related anime/manga the site just breaks completely, it won't load any new pages, it just keeps displaying the same page despite the URL changing fine.  Reload fixes it. Sometimes the navigation bar even gets gray.  
It even happens in a private window with no other extensions, private window also caused Automail to use default settings.

Browser: Brave (Version 1.18.78 Chromium: 87.0.4280.141 (Official Build) (64-bit))
Script manager: Tampermonkey (v4.11)

**Reproduce**
It seems kinda random to me but it still happens consistently, just not always the same way.
- Go to a users anime/manga page
- Click on a anime/manga (like Attack on Titan)
- Click on source/adaption repeatedly to switch back and forth (or just generally switching between related anime)
- Usually it happens on the second time already

**Console**
```
remind hoh to update the commonUnfinishedManga list
userscript.html?name=Automail.user.js&id=<id>:17728 Automail 9.97.6
[Violation] 'setTimeout' handler took 82ms
main.b3506417.js:1 Cache enabled: v21
animelist:1 Failed to decode downloaded font: https://anilist.co/fonts/element-icons.2fad952a.woff
animelist:1 OTS parsing error: invalid version tag
<3 errors from adsbygoogle.js>
5[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>

chunk-vendors.93654cf8.js:17 DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Object.mi [as insertBefore] (https://anilist.co/js/chunk-vendors.93654cf8.js:17:41989)
    at E (https://anilist.co/js/chunk-vendors.93654cf8.js:17:46452)
    at T (https://anilist.co/js/chunk-vendors.93654cf8.js:17:47172)
    at a.__patch__ (https://anilist.co/js/chunk-vendors.93654cf8.js:17:48314)
    at a.t._update (https://anilist.co/js/chunk-vendors.93654cf8.js:17:26954)
    at a.r (https://anilist.co/js/chunk-vendors.93654cf8.js:17:27777)
    at nr.get (https://anilist.co/js/chunk-vendors.93654cf8.js:17:30645)
    at nr.run (https://anilist.co/js/chunk-vendors.93654cf8.js:17:31378)
    at Zn (https://anilist.co/js/chunk-vendors.93654cf8.js:17:29585)
    at Array.<anonymous> (https://anilist.co/js/chunk-vendors.93654cf8.js:17:12740)

main.b3506417.js:1 Uncaught (in promise) TypeError: Cannot read property 'status' of undefined
    at main.b3506417.js:1
    at Generator.throw (<anonymous>)
    at r (chunk-vendors.93654cf8.js:9)
    at c (chunk-vendors.93654cf8.js:9)
```

**Comment by hohMiyazawa** [comment]
Just noting that the error is originating from "chunk-vendors.93654cf8.js", which is native Anilist.
That's not enough to say that Automail is not the cause though.

Working theory: Automail is changing/deleting/moving an HTML node in the dodument. which the native anilist javascript code assumes to always be unchanged.

**Comment by blueYOSHI9000** [comment]
Just realized I didn't mention it, it does not happen without Automail

**Comment by hohMiyazawa** [comment]
That gives this slightly higher priority.

**Comment by hohMiyazawa** [comment]
I can however not reproduce this with the steps provided.

Task 1: Find reproduction steps that reproduces the issue consistently.

**Comment by blueYOSHI9000** [comment]
That's the thing, for me it's really consistent and I don't know what causes it to only happen to me. [I did record a video of it though](https://www.youtube.com/watch?v=ZqPDF5xwHV4) (I didn't show console since I don't know if there's some identifying info in there but the "Failed to execute 'insertBefore' on 'Node'" error is always there, the others aren't always there so they're probably unrelated). I know a video isn't exactly the most useful thing but it's the best I can do at the moment.
I forgot to show it in the video but extensions are all disabled, Brave Shield was disabled as well.

**Comment by hohMiyazawa** [comment]
@blueYOSHI9000 Thanks. Perhaps it is caused by some specific combination of Automail modules. Could you screenshot your settings at https://anilist.co/settings/apps?

**Comment by hohMiyazawa** [comment]
Alternatively, in v9.97.8, I have included a button on the bottom of the settings page to export debug info.

**Comment by blueYOSHI9000** [comment]
[Heres](https://pastebin.com/zRQeE8KX) the file on pastebin. Though in the video I did use private browsing which should've caused it to use default settings but it happens with the linked settings as well.

**Comment by hohMiyazawa** [comment]
From the file, I notice that you aren't signed in with the script.
If you want to, can you confirm that things are still broken if signed in?
Obviously, the script is designed to work without a login too, but this may help track down what's wrong.

**Comment by blueYOSHI9000** [comment]
I just signed in and it still happens, same error in the console too.

**Comment by nate-moo** [comment]
it happens for me too, 
picture of console: 
![image](https://user-images.githubusercontent.com/40650681/107604186-3ed55b80-6bfd-11eb-9e20-bf15373a2c93.png)
video demonstration:
https://user-images.githubusercontent.com/40650681/107604194-44cb3c80-6bfd-11eb-8550-c6ccb09ed262.mp4

**Comment by hohMiyazawa** [comment]
Managed to reproduce this in an environment.
Appears to be browser specific.

**Comment by hohMiyazawa** [comment]
Solved.
It was a tricky combination of site code, chrome, google ads, adblockers and automail.
A nasty heisenbug.
