### ISSUE TITLE
Build on windows

### ISSUE THREAD

**Issue by hohMiyazawa** [hohMiyazawa/Automail#5]
Currently, the build chain depends on shell utilities.
Someone who knows windows should make a way to build it there too.

**Comment by Reinachan** [comment]
I got it working by:
Installing `git` first as that also adds `git bash` (application) which you can run by searching it from the start menu.
Then install make with chocolatey (install chocolatey first if you haven't). In the terminal, run `choco install make`
After that I installed [GoW](https://github.com/bmatzelle/gow/wiki)

With all that installed, just open `git bash`, and do `cd /c/path/to/project/folder/src` 
(replace c with the drive letter your project is in)

Then run `make -f makefile`
