### ISSUE TITLE
More stats feature broke again.

### ISSUE THREAD

**Issue by Repulles** [hohMiyazawa/Automail#54]
It's probably due to AniList going down today.
The site went back up but more stats feature is infinitely "loading..."

**Comment by hohMiyazawa** [comment]
During ddos attacks against the site, it's common for Josh to turn off the API.
Without the API, quite a few Automail modules will stop working.

Perhaps some hardening can be done, making as many modules working as normal even without API access, but that's not a priority.
At the very least, experimenting with that right now would be frustrating, with the site constantly browning out.

**Comment by hohMiyazawa** [comment]
Yes, seems to work now that the site is back up.
