### ISSUE TITLE
Random feature requests

### ISSUE THREAD

**Issue by 1234abcdcba4321** [hohMiyazawa/Automail#62]
After having used this a bit, these are some things I think would be nice to have.

1. Genre/tag lists - column to show amount of entries under it have a valid rating, or a setting to change the behaviour of count to that.
A weighted mean score (by duration / chs read, though idk how those would mix together on the combined anime/manga list) would also be cool.

2. Improved list compare page - ability to normalize people's scores (simplest would be the normalization from more stats -> check compatibility = (x-mean)/stdev) (as it is now I mainly only use it for csv export so that I can operate with the scores after manually normalizing).
Side note: I think the "abs. deviation" option should have its outer square root removed.

3. General text descriptions of stats - The meaning of rating entropy (in more stats), and the numbers in autorecs/check compatibility are pretty hard to figure out. (I haven't found anything else that I couldn't figure out with a bit of playing around.)

4. Automatically set list view mode - I don't think this is reasonable to do because if it was you probably would've done it already, but have a way to automatically set people's list view to a specific one (i always use the compact list view but it's annoying needing to switch to it when others don't set it to that)

5. Ability to json export anyone's list - You can do this with an external tool (or list compare if you try hard enough), but it'd be nice to be able to do it more easily.

**Comment by hohMiyazawa** [comment]
https://github.com/hohMiyazawa/Automail/commit/0216e33d50c0f9e97be9c7f6547450b6ab2af630 #6

**Comment by hohMiyazawa** [comment]
Some more text descriptions added -3

**Comment by hohMiyazawa** [comment]
Normalized ratings added -2

**Comment by hohMiyazawa** [comment]
I can't find a way where -4 works nicely.
And -1 must be part of a stats cleanup.
