### ISSUE TITLE
Socials feature 

### ISSUE THREAD

**Issue by animenutellaa** [hohMiyazawa/Automail#67]
I saw other feature requests on here so I thought might as well try.

I love the social aspect of anilist so I used this website called anifriends https://yase.netlify.app/anifriends/ but it recently stopped working. 
it wasn't much though, it only allowed you to view the users that don't follow you back and the users that do follow you. 
I don't know much about how automail works so I don't know if this is possible?

along with this, is it possible to add a feature where you can sort your following and followers from recent followers to older followers because the default one is alphabetical.

**Comment by hohMiyazawa** [comment]
This thing actually sorta exists already. If you go to your "social" tab, there's a little blue button with two arrows on it.
When you click it, it will show who follows back and who don't.

I don't see sorting followers in chronological order to be possible, as Anilist doesn't provide that information. In theory, one could filter through all notifications to collect the dates, but that's hard.

**Comment by nutellaaaaa** [comment]
OOOOH so that's what that blue arrow does, when i clicked it before i didn't see any difference before but now that i look properly, I see it. 

and yea I've done that but it only shows the notifications of when they followed you, its what i did to find my first follower but i you can't really do the same with people that you followed.

anyway tysm, the unfollow thing was what i wanted :)

**Comment by animenutellaa** [comment]
> When you click it, it will show who follows back and who don't.

um so it says the limit is 600 and i follow like 800+ people lol is there any way to fix or extend this limit?

**Comment by hohMiyazawa** [comment]
Yeah, by writing better page handling.
Will get to it eventually.

**Comment by hohMiyazawa** [comment]
Bandaid solution: grab the number from the "add follow count" stuff, and just go with it.
Works for more than 600, but will eventually fail at some points due to API limits.

**Comment by animenutellaa** [comment]
yayy ty

**Comment by animenutellaa** [comment]
I just checked and it still doesnt work past around after the 296th user so yeah sadly it doesn't even work till 600 :(

i thought maybe it was just that one time but it happens everytime 😞

**Comment by hohMiyazawa** [comment]
Make sure to scroll the whole list into view first!

**Comment by animenutellaa** [comment]
> Make sure to scroll the whole list into view first!

yeah i tried that too, just tried it again just in case and nope it doesn't work even after i scroll all the way to the bottom and then click it

**Comment by hohMiyazawa** [comment]
Will look into it later.

**Comment by hohMiyazawa** [comment]
Replaced the entire thing with "Add separate tabs on the social page for various types of followers".
