### ISSUE TITLE
Customizing Global Feed CSS and/or Two Column Feed

### ISSUE THREAD

**Issue by Adaptz** [hohMiyazawa/Automail#72]
With CSS letting you edit your profile layout and design, it made me wonder if this would be possible for the global feed. It would be a nice addition to Automail and it would give a whole new option of customization. Also adding on to this idea, the ability to have a two column global feed would also be very advantageous. Having to scroll down for ages with each section loading slower and slower looking at posts gets very annoying and with two column global feed it would require a lot less scrolling and loading plus it would look much nicer in my opinion. My knowledge in code is very basic so I have no clue if this would be possible but it for sure would be a nice addition.

**Comment by hohMiyazawa** [comment]
The difference between profile customization and customizing the rest of the site is sharing it with others.

That is, the heavy lifting Automail does is making your profile theme visible to other people using Automail.

If you just want to tweak the site's style for yourself, a [userstyle manager](https://addons.mozilla.org/en-US/firefox/addon/styl-us/) is a much more suitable tool for the job than this script.

That said, you can actually use Automail to add general CSS, by adding a ``css/<your css here>`` line in the title alias editor.

As for a two-column mode, sure, that should be relatively easy to add as an optional module. You would have to wait for me to get in the mood for spending my free time on that though.

**Comment by Adaptz** [comment]
Ok cool thank you so much! I also had another idea just now if you ever feel like doing a mutual friends feature.

**Comment by hohMiyazawa** [comment]
Isn't mutual friends already a thing?

**Comment by Adaptz** [comment]
No I don't believe so unless we are talking about different things in which case I just meant an extra tab in the social section that would display all the friends that you have in common with the specific profile you are viewing. Typing that out made it sound a lot more complicated than I initially was thinking lol.

**Comment by hohMiyazawa** [comment]
Ah, I see.
A bit more tricky, but sounds doable.

**Comment by animenutellaa** [comment]
Ooh yes this feature sounds nice, I’d like to request it as well.

**Comment by hohMiyazawa** [comment]
@animenutellaa Actually, I should probably just scrap the existing broken thingy, and just make something that does both.

**Comment by hohMiyazawa** [comment]
Added the mutuals thing.

**Comment by Adaptz** [comment]
Nice doesn't seem to be working for me tho somehow I don't have all the same friends as myself and I clicked on someones page and had like 600 mutuals even though I only have like 30 friends

**Comment by hohMiyazawa** [comment]
Check https://anilist.co/settings/apps and make sure you're on at least 9.99.29

**Comment by Adaptz** [comment]
Yeah I did to be sure but it wouldn't have even shown it if I wasn't on the right version tho

**Comment by hohMiyazawa** [comment]
Not so, there were a few bugs in a couple of versions that were live for some minutes.

Be also aware that "mutuals" doesn't mean exactly the same as in your proposal. You did perhaps mean to use "shared following" or "shared followers".

**Comment by hohMiyazawa** [comment]
A few minor bugs with the tab switching tho, bundling those fixes with 9.99.30

**Comment by animenutellaa** [comment]
wait it says im on 9.99.9?

**Comment by Adaptz** [comment]
Yeah what else would mutuals mean lol

**Comment by Adaptz** [comment]
I see you added what I was talking about! Looks good thanks!

**Comment by hohMiyazawa** [comment]
I used "mutuals" for the set of users on both the following and followers list of someone.

Better terminology welcome:
https://github.com/hohMiyazawa/Automail/blob/bbaf1522fae329e3b3b8cc8464dd2ed2ca5bc860/src/data/languages/English.json#L158

**Comment by animenutellaa** [comment]
i think what he meant by mutuals was when u look at someone else's social tab, then it shows u people u follow that also follow this person so like all the people that both of you know. for example on Instagram, it says Followed by username, username etc when u go on someones profile.

**Comment by hohMiyazawa** [comment]
Yes, that functionality is there, I just couldn't call everything "mutuals".

**Comment by hohMiyazawa** [comment]
Two column layout available as "Split the home feed into two columns" in v9.99.31
