### ISSUE TITLE
Bug With Two Column Home Feed

### ISSUE THREAD

**Issue by Adaptz** [hohMiyazawa/Automail#75]
![image](https://user-images.githubusercontent.com/84076017/118219652-8a3b1800-b43f-11eb-9773-d08a97f66e7a.png)

This doesn't adjust when two column home feed is turned on

**Comment by hohMiyazawa** [comment]
[weird hack] is very justified in this case.
Post a screenshot of what's wrong, but it likely has nothing to do with the two-column view.

**Comment by Adaptz** [comment]
![image](https://user-images.githubusercontent.com/84076017/118349552-f472bc00-b516-11eb-8ad2-a30123430f76.png)
I think because the columns move the other sections over a bit but the setting doesn't account for it.
