### ISSUE TITLE
Post resize in activity feed

### ISSUE THREAD

**Issue by Cookietogo97** [hohMiyazawa/Automail#76]
Would it be possible to adjust the height of posts in the activity feed in a way that fits all the content of the post without making me scroll within the post? I would like to see all the content of a post at once if it would fit on my screen without scrolling anyways. I don't care if a single post takes up all the space on my screen.

I'm sorry if that is already a feature and I just couldn't find it.

**Comment by hohMiyazawa** [comment]
https://github.com/hohMiyazawa/Automail/commit/b8d5180c8e1450f75dad52ad9b53215147ffbcda

Checking if posts will fit the screen is a really hairy problem, especially since they are already part of a scrollable feed.

But just displaying them in full is pretty simple. Implemented.
