### ISSUE TITLE
Empty gap between navbar and rest of website

### ISSUE THREAD

**Issue by WildManiac** [hohMiyazawa/Automail#77]
There is an empty gap between the navigation bar and the rest of the website. This appears with the extension and userscript. Reverting settings back to default did not remove the gap.

The below screenshot was taken with the userscript enabled, on the homepage.
![Screenshot_2021-05-18 Home · AniList](https://user-images.githubusercontent.com/11233971/118743734-ed9ebe80-b820-11eb-8581-662c6e604375.png)

The below screenshot was take with the userscript disabled, on the homepage.
![Screenshot_2021-05-18 Home · AniList(1)](https://user-images.githubusercontent.com/11233971/118743977-79b0e600-b821-11eb-8e0f-68ddd11d4bf4.png)

**Comment by hohMiyazawa** [comment]
Reproduced, and likely solved.

Will go live when I have confirmed that nothing else is affected.

**Comment by hohMiyazawa** [comment]
live.
