### ISSUE TITLE
"$" mark on list

### ISSUE THREAD

**Issue by jenduis** [hohMiyazawa/Automail#78]
![image](https://user-images.githubusercontent.com/66085054/119231573-3e1c6180-bb2a-11eb-8462-e784b0a4783f.png)
![image](https://user-images.githubusercontent.com/66085054/119231693-de728600-bb2a-11eb-8020-345a646c9bce.png)

Well, this isn't an issue at all but I think It's strange because I've never seen this before. This strange $ mark appears next to some of my friends list. $ does nothing, there's no extra information when I hover above it (unlike rewatches and notes) and I can select copy or paste this $ mark. His nickname is Verxasents, he doesn't use the script and he didn't even know about it until I've mentioned this thing to him. 

Sorry for taking your time.

**Comment by hohMiyazawa** [comment]
It is a feature that lets people view advanced scoring scores

> there's no extra information when I hover above it

Are you sure about that? On hover, it should display the advanced score categories. (works on my machine)

**Comment by jenduis** [comment]
Yes I'm sure It's just a normal unicode character instead of a feature.

**Comment by hohMiyazawa** [comment]
It being a normal unicode character has nothing to do with anything.

Can you make really sure that hovering over a $ reveals no title text? (try several different ones!)

![advancedscores](https://user-images.githubusercontent.com/58218853/119231936-78363500-bb23-11eb-82e4-252108849d61.png)

**Comment by jenduis** [comment]
![image](https://user-images.githubusercontent.com/66085054/119231999-2ba32780-bb2c-11eb-8e65-0f060cded8f0.png)
Yeah it works now sorry for taking your time.

**Comment by hohMiyazawa** [comment]
I should probably make the "$" unselectable, thanks for pointing out that.
