### ISSUE TITLE
Some settings in list compare don't ignore unrated shows

### ISSUE THREAD

**Issue by 1234abcdcba4321** [hohMiyazawa/Automail#79]
On the custom list compare page, the "median", "difference", "minimum", "maximum", "std. deviation", and "abs. deviation" options take into account entries that have a rating of 0, even though it shouldn't.

**Comment by hohMiyazawa** [comment]
That's pretty major if true. Let me check the code.

**Comment by hohMiyazawa** [comment]
Can't reproduce this.
Can you give a specific example (screenshot, ideally), where you point out the difference between actual behaviour and expected behaviour?

**Comment by 1234abcdcba4321** [comment]
https://cdn.discordapp.com/attachments/416769056042123269/847600752767008808/unknown.png
Those first two entries have a 0-rated entry, which impacts the median to not be what it's supposed to be (that being 99 and 96.5, respectively). (The third one doesn't have a 0-rated entry, and so gives the correct result.)

https://cdn.discordapp.com/attachments/416769056042123269/847601336219467836/unknown.png
This one has it set on minimum. The 0 entries cause the minimum for that show to be 0.

**Comment by hohMiyazawa** [comment]
Ah, I see. It goes wrong for *unrated* entries, not all ones.

**Comment by hohMiyazawa** [comment]
I think I found most of them.
