### ISSUE TITLE
Custom Background 

### ISSUE THREAD

**Issue by Alphaheat** [hohMiyazawa/Automail#8]
I'm having difficulty getting the custom background to work. Under the Apps tab at the bottom, you gave out some examples of different backgrounds that can be used. I tried testing it with the color red and I see the actual CSS line in my profile bio but after going back to my profile page, nothing changes. 

For example, if I type in "red" in the box located at the App tab, I will get this CSS line in my profile bio: 

`<!--{"background":"red"}-->`

Going back to my profile page, nothing is changed. I've tried this using hex color codes and images and still, nothing works.

**Comment by hohMiyazawa** [comment]
Can confirm there's a regression here.
Will try to see what's happened. Likely a subtle module migration error.

**Comment by hohMiyazawa** [comment]
It's working for me on the latest build now.
Be aware when testing, that there's aggressive caching of backgrounds. Changes may not show up right away.
