### ISSUE TITLE
Issue with list rating +/- buttons

### ISSUE THREAD

**Issue by 1234abcdcba4321** [hohMiyazawa/Automail#80]
1. When "Give whole numbers a ".0" suffix when using the 10 point decimal scoring system" is enabled, the +/- buttons still move as if the .0 wasn't added when it's a whole number.
2. On 10 point decimal, the - button stops working when the rating is 1.0 or lower (and the + at 0.8 or lower). It should be able to go all the way down to 0.1.

**Comment by hohMiyazawa** [comment]
2) looks like I just forgot to update minScore and maxScore for that scenario. Will fix.

**Comment by hohMiyazawa** [comment]
2) done. Not sure how to deal with 1)

**Comment by hohMiyazawa** [comment]
1. https://github.com/hohMiyazawa/Automail/commit/f8cd3583e41934cf2f0b03e926763265ee888207
