### ISSUE TITLE
custom css box 

### ISSUE THREAD

**Issue by animenutellaa** [hohMiyazawa/Automail#81]
- [ ] Idk if this is possible at all but i use the place where u enter your CSS code quite alot as i test most of it over there so if i u can and have some time, Is there a way to just improve that area altogether, like for example when i enter my custom css in discord, the box to input stuff is alot better as it has alot more functionality like just css language inputting features like different colors line number, easily scroll to area u want, detatched window etc shown in image below. 

- [ ] If it's not possible or might take a little while then could you bring back the thing that was there before? (It let me easily enlarge it) cuz everytime i go there, the default size is really small for the box and it takes me a good minute or two every single time just to get my cursor at the right position for it to turn into a diagonal arrow so that i can enlarge the box, it is pretty annoying lol.

![Discord 30_05_2021 23_51_53](https://user-images.githubusercontent.com/82683011/120122799-15880d80-c1a3-11eb-9a90-27fb0350b807.png)

**Comment by hohMiyazawa** [comment]
How much of a fully featured texteditor it should be, I'm unsure about.

The resize thing is probably due to some of the scrollbar styling from Reina. Not my area of expertise.

**Comment by animenutellaa** [comment]
Can't really say i know all the features so as much as you're willing to do! The ones i mentioned are the ones i want to request but i think being able to open the css text editor in a detached window or just open it in something like visual studio code and being able to sync it would make everything a lot easier since that would basically give u all the features!

**Comment by animenutellaa** [comment]
um i just saw the message under the box and idk how to link a stylesheet at all

**Comment by OfficialBispo** [comment]
@animenutellaa The editor that is showed on your image seems to be [Monaco Editor](https://github.com/microsoft/monaco-editor), the editor that is used on Visual Studio Code. I doubt Hoh can add it to Automail tho.

> um i just saw the message under the box and idk how to link a stylesheet at all

You just need to add on the CSS box:
```css
@import url("https://www.w3schools.com/w3css/4/w3.css")
```
with the link of your CSS file.

**Comment by hohMiyazawa** [comment]
@OfficialBispo Actually, I've added code that makes the syntax:

```
https://www.w3schools.com/w3css/4/w3.css
```

valid too. That is, just an URL with nothing else.

**Comment by animenutellaa** [comment]
@OfficialBispo Thank you, at first i was trying to figure out how github pages work but it was just confusing so i found out you can do it with w3 schools spaces, i've tried it and it works.
