### ISSUE TITLE
Issue with "Colour code the right border of activities by media status" setting

### ISSUE THREAD

**Issue by WildManiac** [hohMiyazawa/Automail#83]
It appears that there is an issue with formatting the color bar when "Colour code the right border of activities by media status" and "Split the home feed into two columns" are enabled. The following are 2 examples of what I am seeing. Notice that the color bar takes the height of the tallest "entry" in the row, regardless of whether or not it is correct.

![2021-06-03 17 21 23 anilist co 5edaa44fab42](https://user-images.githubusercontent.com/11233971/120713852-7b6ce180-c490-11eb-9b3e-aa9640c57e71.png)
![2021-06-03 17 15 15 anilist co ec697f79f99e](https://user-images.githubusercontent.com/11233971/120713861-7d36a500-c490-11eb-81c9-7ee61aee510f.png)

**Comment by hohMiyazawa** [comment]
A fix for this is now live.
