### ISSUE TITLE
Suggestion: Automatically mark hentai entries as Private

### ISSUE THREAD

**Issue by FateXBlood** [hohMiyazawa/Automail#84]
This is something I would love to have cause there are times when I update an 18+ entry and want to keep it private rather than public. I know the "Private" feature exists, so I guess this should be easy to implement?

**Comment by hohMiyazawa** [comment]
Automatically changing editor data is slightly dangerous.

Can you give a small list of example scenarios, and what you want to happen in each of them?

**Comment by FateXBlood** [comment]
@hoyMiyazawa

Let's consider the following scenarios:

1.  I go to the AniList website and I click on a hentai entry, let's say [Jitaku Keibinn](https://anilist.co/anime/98058/Jitaku-Keibiin/). I just go ahead and mark it as completed.
2. Now, what I would want the script to do is, to automatically mark it as private for me, which is already present in the editor menu. This way, I wouldn't have to mark it manually on all hentai entries. 
3. And also an option that would be helpful is something that can mark all the existing hentai entries in the list as Private.

I hope this doesn't seem like a selfish suggestion, but I desperately need something that can hide hentai series in one go.

**Comment by hohMiyazawa** [comment]
I think I get what you want.

It's a reasonable thing to implement in therms of complexity, but I see one big problem:
**Reliability**
The script would have to do something like this:
1. Listen for the editor to show up
2. Determine that the entry currently being being edited is hentai
3. Change the editor data.

Each of those steps could easily fail (example failure mode: the script sends an API call to ask if this media is hentai, but while it's waiting for the answer, you have already clicked the save button and the script is too late to act).

So you could never feel *safe* that the script has actually done its job, and hentai entries could awkwardly slip into your feed without you noticing for several minutes.
So realistically you will always nervously be double checking that the checkebox autochecks, always go back to your feed to make sure no post was made. And is the script really saving you any effort then?

**Comment by FateXBlood** [comment]
I guess not. But I always check my profile before using AL so I can check if there has been a Hentai entry on my profile.
But, I guess this is something that AniList themselves will have to work on.

**Comment by hohMiyazawa** [comment]
A native version of this could indeed be much safer.

If some reliable way of making this comes to mind, I will probably make it. But haven't got anything like that so far.
