### ISSUE TITLE
Custom title aliases don't override short romaji titles

### ISSUE THREAD

**Issue by nfitzen** [hohMiyazawa/Automail#89]
I'm using Automail 9.99.41, and the title's fairly self-explanatory.

As an example, the following are my current title aliases:

```
/anime/21355/Re:ZERO
/anime/112301/Maou Gakuin no Futekigousha
```

The entry for <cite>Maou Gakuin no Futekigousha</cite> works, but the one for <cite>Re:ZERO</cite> doesn't, instead using the case of the short romaji title. When I turn off short romaji titles, the entry for <cite>Re:ZERO</cite> works again.

I also tried doing this by adding `/anime/30/NGE`, and it still shows up as "Evangelion."

**Comment by hohMiyazawa** [comment]
Looks like the priorities were swapped. Fixed.
