### ISSUE TITLE
Too many options?

### ISSUE THREAD

**Issue by hohMiyazawa** [hohMiyazawa/Automail#9]
There are currently ridiculously many options. Splitting them into tabs helped a little, but is the settings page hard to navigate at the moment?

**Comment by Z3ROGRAV1TYx** [comment]
Would +1 for a "Newly added" tab too.

**Comment by hohMiyazawa** [comment]
Hadn't really thought about that. That would make it much easier to find what modules where added.
I will think about a way to implement that, but adding a category should be enough.

**Comment by hohMiyazawa** [comment]
"Newly Added" tab added.

**Comment by hohMiyazawa** [comment]
Seems like tabs helped enough.
