### ISSUE TITLE
"failed to save custom CSS"

### ISSUE THREAD

**Issue by Y4KS4** [hohMiyazawa/Automail#90]
It pop ups every single time when i try to submit the code. All i did before was updating automail

**Comment by hohMiyazawa** [comment]
Post the code so I can try reproducing it.

**Comment by hohMiyazawa** [comment]
Since you closed this issue, is it working for you in the current version?

**Comment by Y4KS4** [comment]
i mean i forgot about github stuff XD when i had this issue at first i had to restart my router and it worked. not it failed again but not for my but for everyone so I guess some maintnance is happening or so

CSS was working fine today but now it just stopped so I thought maybe there was some sort of update
