### ISSUE TITLE
Add option to batch delete Notes on anime/manga entries

### ISSUE THREAD

**Issue by Moelancholy** [hohMiyazawa/Automail#91]
Functionality as stated in the title. Not sure whether it should be in the "Various Statistics" dropdown on the expanded stats page or somewhere else. Batch nuking old tags from e.g. MAL importing or other escapades to start and organise with a clean slate (e.g. encoding/fansubbing purposes) without the pain of manually deleting old Notes to make the tags lists usable would be great.

I posted a comment about this on your AL profile but deleted it in favour of this issue. Feel free to ignore that notif on AL.

**Comment by hohMiyazawa** [comment]
There's some inherit danger in mass deletion.
Won't make this until I'm 100% sure it works as intended.

**Comment by Koopzington** [comment]
I did a little testing and wrote a little something and tested it with Moe and it seemed to be working fine.
https://koopz.rocks/notes-cleaner.html
Feel free to look at the code.
The basic steps that'd need to be done for this task are:
1. Retrieve the `MediaListCollection` of the user in question
2. Stitch together an array of `MediaList.id` (not to be confused with the `Media.id`
3. Execute the `UpdateMediaListEntries` mutation, passing the array of `MediaList.id` and `notes: ""` as arguments, meaning only the `MediaList.notes` field will be updated.
I don't know if there are any limitations on how many IDs you can pass to the mutation but Moe successfully ran it with 401 and in the past i also queried activities of a user, passing IDs of several thousand anime with a single query so i don't think there are any.
I also doubt there's going to be any accidents involving deleting entries from user lists as there's other mutations called `DeleteMediaListEntry/ies` specifically for this purpose.

**Comment by hohMiyazawa** [comment]
That's the best type of feature requests, the ones where I don't have to write any code :)

Can I get a license for it, so I can convert into a query for the "Various statistics" section?
I haven't written any documentation for how those queries work, so I don't recommend spending time trying.

**Comment by Koopzington** [comment]
how would we go about this as i'm a major noob on licensing, in fact i wouldn't even consider this bit of code worthy enough to be slapped on with one of those fat walls of text and planned to delete it after the feature is implemented into Automail anyways.

**Comment by hohMiyazawa** [comment]
Eh, the header says "copyright hoh and the Automail contributors", so just saying in this thread that you're contributing the code should be good enough.

**Comment by Koopzington** [comment]
I hereby give you permission to use the code available under the temporary url https://koopz.rocks/notes-cleaner.html
for free usage and modification without any conditions under any use.

**Comment by hohMiyazawa** [comment]
https://github.com/hohMiyazawa/Automail/commit/3ff80774535d36a85201a8a1fe3a593c1c4d2607
